"""The objective being minimized. DO NOT edit this file — it is part of the
evaluation contract."""

import math


class Objective:
    """Rastrigin function on the domain [-5.12, 5.12]^2 with an evaluation budget."""

    LOWER = -5.12
    UPPER = 5.12
    DIM = 2

    def __init__(self, budget):
        self.budget = budget
        self.evals = 0

    def __call__(self, x):
        if self.evals >= self.budget:
            raise RuntimeError("evaluation budget exceeded")
        self.evals += 1
        a = 10.0
        return a * self.DIM + sum(xi * xi - a * math.cos(2 * math.pi * xi) for xi in x)
