apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veritly

resources:
  - 00-namespace.yaml
  - postgres.yaml
  - 01-relay.yaml
  - 02-opencode-api.yaml
  - 02b-opencode-frontend.yaml
  - 03-executor.yaml
  - 03c-executor-sticky-ingress.yaml
  - 03b-executor-dev.yaml
  - 04-ingress.yaml

images:
  - name: opencode-veritly-relay
    newName: registry.digitalocean.com/veritly-registry/relay
    newTag: latest
  - name: opencode-veritly-api
    newName: registry.digitalocean.com/veritly-registry/opencode-api
    newTag: latest
  - name: opencode-veritly-frontend
    newName: registry.digitalocean.com/veritly-registry/opencode-frontend
    newTag: latest
  - name: opencode-veritly-executor
    newName: registry.digitalocean.com/veritly-registry/executor
    newTag: latest
  - name: opencode-veritly-executor-dev
    newName: registry.digitalocean.com/veritly-registry/executor
    newTag: dev
