export const ACTIVITY_VERBS = [
  "mogging",
  "glazing",
  "larping",
  "canoodling",
  "scheming",
  "fuming",
  "coping",
  "seething",
  "plotting",
  "yapping",
  "fumbling",
  "malding",
  "grandstanding",
  "doomscrolling",
  "clowning",
  "gremlining",
  "goblining",
  "waffling",
  "dillydallying",
  "catastrophizing",
  "overthinking",
  "underdelivering",
  "vibecoding",
  "yak-shaving",
  "bikeshedding",
  "nitpicking",
  "procrastinating",
  "overengineering",
  "spaghettiweaving",
  "bugfarming",
  "cachepoisoning",
  "stacktracing",
  "tokenburning",
  "contextstuffing",
  "promptwrangling",
  "diffdivining",
  "lintworshipping",
  "testdodging",
  "mergebegging",
  "branchhaunting",
  "commitcosplaying",
  "semicolonhoarding",
  "typesquinting",
  "regexsummoning",
  "dependencyjuggling",
  "logstaring",
  "packetwhispering",
  "daemonpoking",
  "terminalpeacocking",
  "sandboxrattling",
  "copypasting",
  "tabcollecting",
  "scopecreeping",
  "deadlinehaunting",
  "yakstacking",
  "slopshoveling",
  "codefermenting",
  "pixelslandering",
  "buildgaslighting",
  "syntaxgrooming",
] as const

export function activityVerb(key: string, offset = 0) {
  const hash = Array.from(key).reduce((value, character) => (value * 31 + character.charCodeAt(0)) >>> 0, 0)
  return ACTIVITY_VERBS[(hash + offset) % ACTIVITY_VERBS.length]
}
