#!/usr/bin/env node
/**
 * Redmine Time Entry Loader — Setup
 * 
 * Interactive first-run configuration. Sets up config.json and .credentials.
 * 
 * Usage: node setup.js
 */

import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ═══════════════════════════════════════════════════════════════
// PROMPT HELPER
// ═══════════════════════════════════════════════════════════════

function ask(question, defaultVal = '') {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    const hint = defaultVal ? ` (${defaultVal})` : '';
    rl.question(`  ${question}${hint}: `, answer => {
      rl.close();
      resolve(answer.trim() || defaultVal);
    });
  });
}

function askPassword(question) {
  return new Promise(resolve => {
    process.stdout.write(`  ${question}: `);
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    // Simple stdin read — won't hide input on all terminals, but works cross-platform
    rl.on('line', line => {
      rl.close();
      resolve(line.trim());
    });
  });
}

// ═══════════════════════════════════════════════════════════════
// LOAD EXISTING CONFIG
// ═══════════════════════════════════════════════════════════════

function loadExisting() {
  const config = { baseUrl: 'https://oneadmin.oneinfoconsulting.com', project: '', issueId: '', issueLabel: '', defaultActivity: 'Desarrollo', defaultHours: 8, headless: true };
  const creds = { user: '', pass: '' };

  try {
    const raw = readFileSync(join(__dirname, 'config.json'), 'utf8');
    Object.assign(config, JSON.parse(raw));
  } catch {}

  try {
    const raw = readFileSync(join(__dirname, '.credentials'), 'utf8');
    const user = raw.match(/REDMINE_USER=(.+)/)?.[1]?.trim();
    const pass = raw.match(/REDMINE_PASS=(.+)/)?.[1]?.trim();
    if (user) creds.user = user;
    if (pass) creds.pass = pass;
  } catch {}

  return { config, creds };
}

// ═══════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════

async function main() {
  const { config, creds } = loadExisting();

  console.log('');
  console.log('╔══════════════════════════════════════════════════╗');
  console.log('║       Redmine Time Entry Loader — Setup         ║');
  console.log('╚══════════════════════════════════════════════════╝');
  console.log('');
  console.log('  Press Enter to keep the current value (shown in parentheses).');
  console.log('');

  // ── Credentials ──
  console.log('  ── Credentials ──');
  const user = await ask('  Redmine username', creds.user);
  const pass = await askPassword('  Redmine password');

  // ── Project ──
  console.log('');
  console.log('  ── Project ──');
  const baseUrl = await ask('  Base URL', config.baseUrl);
  const project = await ask('  Project slug (e.g. service-delivery-2026)', config.project);

  // ── Issue ──
  console.log('');
  console.log('  ── Default Issue ──');
  const issueId = await ask('  Issue ID (e.g. 15464)', config.issueId);
  const issueLabel = await ask('  Issue label (e.g. Gestión Interna)', config.issueLabel);

  // ── Defaults ──
  console.log('');
  console.log('  ── Defaults ──');
  const defaultActivity = await ask('  Activity (Desarrollo, Análisis, Reunion, etc.)', config.defaultActivity);
  const defaultHours = await ask('  Hours per day', String(config.defaultHours));

  // ── Summary ──
  console.log('');
  console.log('  ── Summary ──');
  console.log(`  URL:         ${baseUrl}`);
  console.log(`  Project:     ${project}`);
  console.log(`  Issue:       Task #${issueId}: ${issueLabel}`);
  console.log(`  Activity:    ${defaultActivity}`);
  console.log(`  Hours/day:   ${defaultHours}`);
  console.log(`  Username:    ${user}`);
  console.log(`  Password:    ${'*'.repeat(pass.length)}`);
  console.log('');

  const confirm = await ask('  Save this configuration? (Y/n)', 'Y');
  if (confirm.toLowerCase() === 'n') {
    console.log('  ❌ Cancelled.');
    process.exit(0);
  }

  // ── Write config.json ──
  const configData = {
    baseUrl,
    project,
    issueId,
    issueLabel,
    defaultActivity,
    defaultHours: parseInt(defaultHours, 10) || 8,
    headless: config.headless,
  };

  writeFileSync(join(__dirname, 'config.json'), JSON.stringify(configData, null, 2) + '\n');
  console.log('  ✅ config.json saved');

  // ── Write .credentials ──
  const credData = `# Redmine Credentials — generated by setup.js\n# DO NOT COMMIT THIS FILE\nREDMINE_USER=${user}\nREDMINE_PASS=${pass}\n`;
  writeFileSync(join(__dirname, '.credentials'), credData);
  console.log('  ✅ .credentials saved');

  // ── Test login ──
  console.log('');
  const testLogin = await ask('  Test login now? (Y/n)', 'Y');
  if (testLogin.toLowerCase() === 'n') {
    console.log('');
    console.log('  ✅ Setup complete. Run "node load-hours.js" to start loading hours.');
    console.log('');
    process.exit(0);
  }

  console.log('');
  process.stdout.write('  🔐 Testing login...');

  try {
    const { chromium } = await import('playwright');
    const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
    try {
      const page = await browser.newPage();
      await page.goto(`${baseUrl}/login`, { waitUntil: 'networkidle' });
      await page.locator('#username').fill(user);
      await page.locator('#password').fill(pass);
      await page.locator('#login-submit').click();
      await page.waitForLoadState('networkidle', { timeout: 15000 });

      if (page.url().includes('/login')) {
        console.log(' ❌');
        console.log('  Login failed — check your username and password.');
        console.log('  Config saved anyway. Fix credentials and re-run "node setup.js".');
      } else {
        console.log(' ✅');
        console.log('');
        console.log('  🎉 Setup complete! Run "node load-hours.js" to start loading hours.');
      }
    } finally {
      await browser.close();
    }
  } catch (err) {
    console.log(' ⚠️');
    console.log(`  Could not test login: ${err.message}`);
    console.log('  Config saved. Install playwright if needed: npm install playwright');
  }

  console.log('');
}

main().catch(err => {
  console.error('\n❌ Error:', err.message);
  process.exit(1);
});
