#!/usr/bin/env bun

// Legacy v1 color tokens live in these sources. theme.css also defines shared non-color scales, which stay allowed.
const sources = ["../src/styles/colors.css", "../src/styles/theme.css"]

const nonColor = [
  /^v2-/,
  /^font-/,
  /^line-height-/,
  /^letter-spacing-/,
  /^paragraph-spacing-/,
  /^radius-/,
  /^shadow-/,
  /^breakpoint-/,
  /^container-/,
  /^spacing$/,
  /^text-mix-blend-mode$/,
]

const texts = await Promise.all(sources.map((source) => Bun.file(import.meta.dir + "/" + source).text()))

const tokens = [
  ...new Set(
    texts.flatMap((text) => [...text.matchAll(/(?:^|[\s;{])--([a-zA-Z0-9-]+)\s*:/g)].map((match) => match[1]!)),
  ),
]
  .filter((name) => !nonColor.some((pattern) => pattern.test(name)))
  .toSorted()

const output = `// Generated by script/generate-design-lint-tokens.ts
// Do not edit this file manually

export const legacyTokens = [
${tokens.map((name) => `  "${name}",`).join("\n")}
] as const
`

await Bun.write(import.meta.dir + "/../src/design-lint/legacy-tokens.ts", output)

console.log(`Wrote ${tokens.length} legacy tokens`)
