import { z } from "zod/v4";
export declare const codeInterpreterInputSchema: z.ZodObject<{
    code: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    containerId: z.ZodString;
}, z.core.$strip>;
export declare const codeInterpreterOutputSchema: z.ZodObject<{
    outputs: z.ZodOptional<z.ZodNullable<z.ZodArray<z.ZodDiscriminatedUnion<[z.ZodObject<{
        type: z.ZodLiteral<"logs">;
        logs: z.ZodString;
    }, z.core.$strip>, z.ZodObject<{
        type: z.ZodLiteral<"image">;
        url: z.ZodString;
    }, z.core.$strip>], "type">>>>;
}, z.core.$strip>;
export declare const codeInterpreterArgsSchema: z.ZodObject<{
    container: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodObject<{
        fileIds: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>]>>;
}, z.core.$strip>;
type CodeInterpreterArgs = {
    /**
     * The code interpreter container.
     * Can be a container ID
     * or an object that specifies uploaded file IDs to make available to your code.
     */
    container?: string | {
        fileIds?: string[];
    };
};
export declare const codeInterpreterToolFactory: import("@ai-sdk/provider-utils").ProviderDefinedToolFactoryWithOutputSchema<{
    /**
     * The code to run, or null if not available.
     */
    code?: string | null | undefined;
    /**
     * The ID of the container used to run the code.
     */
    containerId: string;
}, {
    /**
     * The outputs generated by the code interpreter, such as logs or images.
     * Can be null if no outputs are available.
     */
    outputs?: ({
        type: "logs";
        /**
         * The logs output from the code interpreter.
         */
        logs: string;
    } | {
        type: "image";
        /**
         * The URL of the image output from the code interpreter.
         */
        url: string;
    })[] | null | undefined;
}, CodeInterpreterArgs>;
export declare const codeInterpreter: (args?: CodeInterpreterArgs) => import("@ai-sdk/provider-utils").Tool<{
    /**
     * The code to run, or null if not available.
     */
    code?: string | null | undefined;
    /**
     * The ID of the container used to run the code.
     */
    containerId: string;
}, {
    /**
     * The outputs generated by the code interpreter, such as logs or images.
     * Can be null if no outputs are available.
     */
    outputs?: ({
        type: "logs";
        /**
         * The logs output from the code interpreter.
         */
        logs: string;
    } | {
        type: "image";
        /**
         * The URL of the image output from the code interpreter.
         */
        url: string;
    })[] | null | undefined;
}>;
export {};
