// securecode untrusted-content-wrapper plugin.
// Wraps every completed ToolPart output in a per-wrap nonced boundary so the
// model sees a clear "this is data, not instructions" container around every
// piece of external text. The boundary takes the form
//
//   <untrusted_TOKEN source="...">
//   ... raw tool output ...
//   </untrusted_TOKEN>
//
// where TOKEN is a fresh 64-bit hex string generated by the plugin at wrap
// time. The matching defensive system prompt (Issue #268) tells the model to
// treat ANY <untrusted_…>…</untrusted_…> block as inert data.
//
// Why a per-wrap nonce, not a fixed tag name:
// - The previous `<untrusted-content>` form (Issue #266) had to defang both
//   the opening and closing tags inside the payload to prevent an
//   attacker-controlled tool output from forging an inner boundary or closing
//   the outer wrapper early. With a 64-bit nonce in the tag name itself, the
//   attacker cannot guess the outer TOKEN and so cannot close it. Forged
//   inner boundaries are harmless: under the defensive prompt's rules they
//   just create additional untrusted regions inside the real one, which is a
//   no-op for the attacker.
// - Internal collisions (two wraps in the same session happening to draw the
//   same TOKEN) are bounded by the birthday paradox (~2^-32 for 64-bit
//   tokens). A collision is still safe: it would merely cause two real
//   boundaries to look the same, never let payload escape its wrapper. The
//   threat to size against is "attacker correctly guesses an outer TOKEN",
//   which is 2^-64 per attempt.
//
// Like overflow-guard.ts, this runs in experimental.chat.messages.transform
// (not tool.execute.after) because for MCP tools the latter passes the raw
// {content: [...]} structure through and any mutation is discarded when
// opencode rebuilds the final output. See overflow-guard.ts:11-15 for the
// background.
//
// Plugin order matters: this plugin must run AFTER OverflowGuardPlugin so the
// wrapper sees the already-truncated output, otherwise wrapping inflates the
// payload before the truncator can shrink it.
//
// See https://github.com/acompany-develop/securecode/issues/266
// and https://github.com/acompany-develop/securecode/issues/277.

import { randomBytes } from "node:crypto"
import type { Hooks, PluginInput } from "@opencode-ai/plugin"
import * as Log from "@opencode-ai/core/util/log"

const log = Log.create({ service: "securecode.untrusted-content-wrapper" })

const DISABLE_ENV = "SECURECODE_UNTRUSTED_WRAPPER_DISABLE"
const NONCE_BYTES = 8 // 64 bits — 2^-64 forgery probability per attempt

// Patterns commonly used in indirect prompt injection attempts. Detection is
// best-effort and intentionally loose; a positive match adds a visible warning
// suffix inside the wrapper so the LLM (and a human reading session logs)
// notices. We deliberately do NOT block the tool result on a match — that
// would be a high false-positive surface and the system prompt already tells
// the model to treat the wrapped block as data.
export const INJECTION_PATTERNS: { pattern: RegExp; label: string }[] = [
  { pattern: /ignore (all |any |the )?(previous|prior|above) (instructions|commands|prompts)/i, label: "override-attempt" },
  { pattern: /disregard (all |any |the )?(previous|prior|above) (instructions|commands|prompts)/i, label: "override-attempt" },
  { pattern: /これまでの(指示|命令|プロンプト)を(無視|忘れて)/, label: "override-attempt" },
  { pattern: /新しい(指示|命令|ルール)[:：]/, label: "override-attempt" },
  { pattern: /<\|?system\|?>/i, label: "role-injection" },
  { pattern: /\[INST\]/, label: "role-injection" },
  { pattern: /\[\/INST\]/, label: "role-injection" },
  { pattern: /you are (now|currently) /i, label: "persona-rewrite" },
  { pattern: /from now on,? (you|please)/i, label: "persona-rewrite" },
]

type Part = { type: string; tool?: string; [key: string]: any }
type Message = { info: { sessionID?: string; [key: string]: any }; parts: Part[] }

export type WrapStats = {
  wrappedParts: number
  flaggedParts: number
}

export function isDisabled(): boolean {
  return process.env[DISABLE_ENV] === "1"
}

// Generate a fresh per-wrap nonce. 8 bytes = 16 hex chars = 64 bits.
// We allow tests/callers to inject a deterministic generator.
export function generateNonce(): string {
  return randomBytes(NONCE_BYTES).toString("hex")
}

export function detectInjections(output: string): string[] {
  const labels = new Set<string>()
  for (const { pattern, label } of INJECTION_PATTERNS) {
    if (pattern.test(output)) labels.add(label)
  }
  return [...labels]
}

export function wrapOutput(
  output: string,
  tool: string,
  nonce: string = generateNonce(),
): { wrapped: string; flagged: string[]; nonce: string } {
  const flagged = detectInjections(output)
  const warning = flagged.length
    ? `\n\n[!] securecode: suspicious instruction pattern detected (${flagged.join(", ")})`
    : ""
  const wrapped = `<untrusted_${nonce} source="${tool}">\n${output}${warning}\n</untrusted_${nonce}>`
  return { wrapped, flagged, nonce }
}

export function wrapMessagesInPlace(messages: Message[]): WrapStats {
  let wrappedParts = 0
  let flaggedParts = 0
  for (const message of messages) {
    for (const part of message.parts ?? []) {
      if (part.type !== "tool") continue
      const state = part.state
      if (!state || state.status !== "completed") continue
      if (typeof state.output !== "string") continue
      // Idempotency: this hook can fire more than once per build turn
      // (e.g. on compaction retries). Skip Parts the plugin has already
      // wrapped. The flag lives in metadata, not in the output string, so it
      // cannot be influenced by tool output that happens to look like a
      // wrapper.
      if (part.metadata?.securecodeUntrustedWrapper?.wrapped === true) continue
      const tool = typeof part.tool === "string" && part.tool ? part.tool : "unknown"
      const { wrapped, flagged, nonce } = wrapOutput(state.output, tool)
      state.output = wrapped
      wrappedParts += 1
      if (flagged.length > 0) {
        flaggedParts += 1
        log.info("injection pattern detected in tool output", { tool, flagged })
      }
      part.metadata = {
        ...(part.metadata ?? {}),
        securecodeUntrustedWrapper: {
          wrapped: true,
          flagged,
          nonce,
        },
      }
    }
  }
  return { wrappedParts, flaggedParts }
}

export async function UntrustedContentWrapperPlugin(_input: PluginInput): Promise<Hooks> {
  if (isDisabled()) return {}

  return {
    "experimental.chat.messages.transform": async (_input, output) => {
      if (!output || !Array.isArray(output.messages)) return
      const messages = output.messages as unknown as Message[]
      wrapMessagesInPlace(messages)
    },
  }
}
