// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	killSidecar: () => __TAURI_INVOKE<void>("kill_sidecar"),
	installCli: () => __TAURI_INVOKE<string>("install_cli"),
	awaitInitialization: (events: Channel) => __TAURI_INVOKE<ServerReadyData>("await_initialization", { events }),
	getDefaultServerUrl: () => __TAURI_INVOKE<string | null>("get_default_server_url"),
	setDefaultServerUrl: (url: string | null) => __TAURI_INVOKE<null>("set_default_server_url", { url }),
	getWslConfig: () => __TAURI_INVOKE<WslConfig>("get_wsl_config"),
	setWslConfig: (config: WslConfig) => __TAURI_INVOKE<null>("set_wsl_config", { config }),
	getDisplayBackend: () => __TAURI_INVOKE<"wayland" | "auto" | null>("get_display_backend"),
	setDisplayBackend: (backend: LinuxDisplayBackend) => __TAURI_INVOKE<null>("set_display_backend", { backend }),
	parseMarkdownCommand: (markdown: string) => __TAURI_INVOKE<string>("parse_markdown_command", { markdown }),
	checkAppExists: (appName: string) => __TAURI_INVOKE<boolean>("check_app_exists", { appName }),
	wslPath: (path: string, mode: "windows" | "linux" | null) => __TAURI_INVOKE<string>("wsl_path", { path, mode }),
	resolveAppPath: (appName: string) => __TAURI_INVOKE<string | null>("resolve_app_path", { appName }),
	openPath: (path: string, appName: string | null) => __TAURI_INVOKE<null>("open_path", { path, appName }),
	createDesignWebview: (url: string, x: number, y: number, width: number, height: number, script: string | null) => __TAURI_INVOKE<null>("create_design_webview", { url, x, y, width, height, script }),
	resizeDesignWebview: (x: number, y: number, width: number, height: number) => __TAURI_INVOKE<null>("resize_design_webview", { x, y, width, height }),
	closeDesignWebview: () => __TAURI_INVOKE<null>("close_design_webview"),
	evalDesignWebview: (script: string) => __TAURI_INVOKE<null>("eval_design_webview", { script }),
	designBridge: (event: string, payload: string) => __TAURI_INVOKE<null>("design_bridge", { event, payload }),
	buildDesignIndex: (root: string) => __TAURI_INVOKE<string[]>("build_design_index", { root }),
	updateDesignIndex: (root: string, paths: string[]) => __TAURI_INVOKE<string[]>("update_design_index", { root, paths }),
	queryDesignIndex: (root: string, component: string | null, classes: string[] | null) => __TAURI_INVOKE<{
	file: string,
	line: number,
	confidence: number,
} | null>("query_design_index", { root, component, classes }),
};

/** Events */
export const events = {
	loadingWindowComplete: makeEvent<LoadingWindowComplete>("loading-window-complete"),
	sqliteMigrationProgress: makeEvent<SqliteMigrationProgress>("sqlite-migration-progress"),
};

/* Types */
export type InitStep = { phase: "server_waiting" } | { phase: "sqlite_waiting" } | { phase: "done" };

export type LinuxDisplayBackend = "wayland" | "auto";

export type LoadingWindowComplete = null;

export type QueryResult = {
		file: string,
		line: number,
		confidence: number,
	};

export type ServerReadyData = {
		url: string,
		username: string | null,
		password: string | null,
	};

export type SqliteMigrationProgress = { type: "InProgress"; value: number } | { type: "Done" };

export type WslConfig = {
		enabled: boolean,
	};

export type WslPathMode = "windows" | "linux";

/* Tauri Specta runtime */
function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: (payload: T) => __TAURI_EVENT.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: (payload: T) => target.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

