export namespace Flag {
  export const CHALICECODE_AUTO_SHARE = truthy("CHALICECODE_AUTO_SHARE")
  export const CHALICECODE_CONFIG = process.env["CHALICECODE_CONFIG"]
  export const CHALICECODE_CONFIG_DIR = process.env["CHALICECODE_CONFIG_DIR"]
  export const CHALICECODE_CONFIG_CONTENT = process.env["CHALICECODE_CONFIG_CONTENT"]
  export const CHALICECODE_DISABLE_AUTOUPDATE = truthy("CHALICECODE_DISABLE_AUTOUPDATE")
  export const CHALICECODE_DISABLE_PRUNE = truthy("CHALICECODE_DISABLE_PRUNE")
  export const CHALICECODE_PERMISSION = process.env["CHALICECODE_PERMISSION"]
  export const CHALICECODE_DISABLE_DEFAULT_PLUGINS = truthy("CHALICECODE_DISABLE_DEFAULT_PLUGINS")
  export const CHALICECODE_DISABLE_LSP_DOWNLOAD = truthy("CHALICECODE_DISABLE_LSP_DOWNLOAD")
  export const CHALICECODE_ENABLE_EXPERIMENTAL_MODELS = truthy("CHALICECODE_ENABLE_EXPERIMENTAL_MODELS")
  export const CHALICECODE_DISABLE_AUTOCOMPACT = truthy("CHALICECODE_DISABLE_AUTOCOMPACT")
  export const CHALICECODE_FAKE_VCS = process.env["CHALICECODE_FAKE_VCS"]

  // Experimental
  export const CHALICECODE_EXPERIMENTAL = truthy("CHALICECODE_EXPERIMENTAL")
  export const CHALICECODE_EXPERIMENTAL_WATCHER = CHALICECODE_EXPERIMENTAL || truthy("CHALICECODE_EXPERIMENTAL_WATCHER")
  export const CHALICECODE_EXPERIMENTAL_EXA = CHALICECODE_EXPERIMENTAL || truthy("CHALICECODE_EXPERIMENTAL_EXA")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }
}
