import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const snapshot = path.join(dir, "src/provider/models-snapshot.js")

async function loadModelsData() {
  if (process.env.MODELS_DEV_API_JSON) return Bun.file(process.env.MODELS_DEV_API_JSON).text()

  try {
    return await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
  } catch (err) {
    console.warn("Failed to fetch models.dev, using cached snapshot", err)
    return Bun.file(snapshot)
      .text()
      .then((text) =>
        text
          .replace(/^\/\/ @ts-nocheck\n\/\/ Auto-generated by build\.ts - do not edit\nexport const snapshot = /, "")
          .trim(),
      )
  }
}

export const modelsData = await loadModelsData()
console.log("Loaded models.dev snapshot")
