export namespace Flag {
  export const OPENDEEPSEEK_AUTO_SHARE = truthy("OPENDEEPSEEK_AUTO_SHARE")
  export const OPENDEEPSEEK_GIT_BASH_PATH = process.env["OPENDEEPSEEK_GIT_BASH_PATH"]
  export const OPENDEEPSEEK_CONFIG = process.env["OPENDEEPSEEK_CONFIG"]
  export const OPENDEEPSEEK_CONFIG_DIR = process.env["OPENDEEPSEEK_CONFIG_DIR"]
  export const OPENDEEPSEEK_CONFIG_CONTENT = process.env["OPENDEEPSEEK_CONFIG_CONTENT"]
  export const OPENDEEPSEEK_DISABLE_AUTOUPDATE = truthy("OPENDEEPSEEK_DISABLE_AUTOUPDATE")
  export const OPENDEEPSEEK_DISABLE_PRUNE = truthy("OPENDEEPSEEK_DISABLE_PRUNE")
  export const OPENDEEPSEEK_DISABLE_TERMINAL_TITLE = truthy("OPENDEEPSEEK_DISABLE_TERMINAL_TITLE")
  export const OPENDEEPSEEK_PERMISSION = process.env["OPENDEEPSEEK_PERMISSION"]
  // Force-disable default plugins in native builds to avoid module resolution issues
  export const OPENDEEPSEEK_DISABLE_DEFAULT_PLUGINS = true
  export const OPENDEEPSEEK_DISABLE_LSP_DOWNLOAD = truthy("OPENDEEPSEEK_DISABLE_LSP_DOWNLOAD")
  export const OPENDEEPSEEK_ENABLE_EXPERIMENTAL_MODELS = truthy("OPENDEEPSEEK_ENABLE_EXPERIMENTAL_MODELS")
  export const OPENDEEPSEEK_DISABLE_AUTOCOMPACT = truthy("OPENDEEPSEEK_DISABLE_AUTOCOMPACT")
  export const OPENDEEPSEEK_DISABLE_MODELS_FETCH = truthy("OPENDEEPSEEK_DISABLE_MODELS_FETCH")
  export const OPENDEEPSEEK_FAKE_VCS = process.env["OPENDEEPSEEK_FAKE_VCS"]
  export const OPENDEEPSEEK_CLIENT = process.env["OPENDEEPSEEK_CLIENT"] ?? "cli"

  // Experimental
  export const OPENDEEPSEEK_EXPERIMENTAL = truthy("OPENDEEPSEEK_EXPERIMENTAL")
  export const OPENDEEPSEEK_EXPERIMENTAL_FILEWATCHER = truthy("OPENDEEPSEEK_EXPERIMENTAL_FILEWATCHER")
  export const OPENDEEPSEEK_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("OPENDEEPSEEK_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const OPENDEEPSEEK_EXPERIMENTAL_ICON_DISCOVERY =
    OPENDEEPSEEK_EXPERIMENTAL || truthy("OPENDEEPSEEK_EXPERIMENTAL_ICON_DISCOVERY")
  export const OPENDEEPSEEK_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("OPENDEEPSEEK_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENDEEPSEEK_ENABLE_EXA =
    truthy("OPENDEEPSEEK_ENABLE_EXA") || OPENDEEPSEEK_EXPERIMENTAL || truthy("OPENDEEPSEEK_EXPERIMENTAL_EXA")
  export const OPENDEEPSEEK_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("OPENDEEPSEEK_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const OPENDEEPSEEK_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("OPENDEEPSEEK_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const OPENDEEPSEEK_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("OPENDEEPSEEK_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const OPENDEEPSEEK_EXPERIMENTAL_OXFMT = OPENDEEPSEEK_EXPERIMENTAL || truthy("OPENDEEPSEEK_EXPERIMENTAL_OXFMT")
  export const OPENDEEPSEEK_EXPERIMENTAL_LSP_TY = truthy("OPENDEEPSEEK_EXPERIMENTAL_LSP_TY")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
