export const KeyCodes = {
  ESC:           "\x1b",
  ENTER:         "\r",
  TAB:           "\t",
  BACKSPACE:     "\x7f",
  SPACE:         " ",

  CTRL_A:        "\x01",
  CTRL_B:        "\x02",
  CTRL_C:        "\x03",
  CTRL_D:        "\x04",
  CTRL_E:        "\x05",
  CTRL_F:        "\x06",
  CTRL_G:        "\x07",
  CTRL_H:        "\x08",
  CTRL_I:        "\x09",
  CTRL_J:        "\x0a",
  CTRL_K:        "\x0b",
  CTRL_L:        "\x0c",
  CTRL_M:        "\x0d",
  CTRL_N:        "\x0e",
  CTRL_O:        "\x0f",
  CTRL_P:        "\x10",
  CTRL_Q:        "\x11",
  CTRL_R:        "\x12",
  CTRL_S:        "\x13",
  CTRL_T:        "\x14",
  CTRL_U:        "\x15",
  CTRL_V:        "\x16",
  CTRL_W:        "\x17",
  CTRL_X:        "\x18",
  CTRL_Y:        "\x19",
  CTRL_Z:        "\x1a",

  CSI_ARROW_UP:    "\x1b[A",
  CSI_ARROW_DOWN:  "\x1b[B",
  CSI_ARROW_RIGHT: "\x1b[C",
  CSI_ARROW_LEFT:  "\x1b[D",
  CSI_HOME:        "\x1b[H",
  CSI_END:         "\x1b[F",
  CSI_INSERT:      "\x1b[2~",
  CSI_DELETE:      "\x1b[3~",
  CSI_PAGE_UP:     "\x1b[5~",
  CSI_PAGE_DOWN:   "\x1b[6~",
  CSI_HOME_ALT:    "\x1b[1~",
  CSI_END_ALT:     "\x1b[4~",
} as const satisfies Record<string, string>
