export declare namespace Flag {
    const OPENCODE_AUTO_SHARE: boolean;
    const OPENCODE_GIT_BASH_PATH: string | undefined;
    const OPENCODE_CONFIG: string | undefined;
    const OPENCODE_CONFIG_DIR: string | undefined;
    const OPENCODE_CONFIG_CONTENT: string | undefined;
    const OPENCODE_DISABLE_AUTOUPDATE: boolean;
    const OPENCODE_DISABLE_PRUNE: boolean;
    const OPENCODE_DISABLE_TERMINAL_TITLE: boolean;
    const OPENCODE_PERMISSION: string | undefined;
    const OPENCODE_DISABLE_DEFAULT_PLUGINS: boolean;
    const OPENCODE_DISABLE_LSP_DOWNLOAD: boolean;
    const OPENCODE_ENABLE_EXPERIMENTAL_MODELS: boolean;
    const OPENCODE_DISABLE_AUTOCOMPACT: boolean;
    const OPENCODE_DISABLE_MODELS_FETCH: boolean;
    const OPENCODE_DISABLE_CLAUDE_CODE: boolean;
    const OPENCODE_DISABLE_CLAUDE_CODE_PROMPT: boolean;
    const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS: boolean;
    const OPENCODE_DISABLE_EXTERNAL_SKILLS: boolean;
    const OPENCODE_DISABLE_PROJECT_CONFIG: boolean;
    const OPENCODE_FAKE_VCS: string | undefined;
    const OPENCODE_CLIENT: string;
    const OPENCODE_SERVER_PASSWORD: string | undefined;
    const OPENCODE_SERVER_USERNAME: string | undefined;
    const OPENCODE_ENABLE_QUESTION_TOOL: boolean;
    const OPENCODE_EXPERIMENTAL: boolean;
    const OPENCODE_EXPERIMENTAL_FILEWATCHER: boolean;
    const OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: boolean;
    const OPENCODE_EXPERIMENTAL_ICON_DISCOVERY: boolean;
    const OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT: boolean;
    const OPENCODE_ENABLE_EXA: boolean;
    const OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number | undefined;
    const OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number | undefined;
    const OPENCODE_EXPERIMENTAL_OXFMT: boolean;
    const OPENCODE_EXPERIMENTAL_LSP_TY: boolean;
    const OPENCODE_EXPERIMENTAL_LSP_TOOL: boolean;
    const OPENCODE_DISABLE_FILETIME_CHECK: boolean;
    const OPENCODE_EXPERIMENTAL_PLAN_MODE: boolean;
    const OPENCODE_EXPERIMENTAL_MARKDOWN: boolean;
    const OPENCODE_MODELS_URL: string | undefined;
    const OPENCODE_MODELS_PATH: string | undefined;
    const OPENCODE_DISABLE_CHANNEL_DB: boolean;
    const OPENCODE_SKIP_MIGRATIONS: boolean;
}
