name: バグ報告
description: 修正すべき問題を報告する
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 説明
      description: 遭遇したバグを説明してください
      placeholder: 何が起きましたか？
    validations:
      required: true

  - type: input
    id: plugins
    attributes:
      label: プラグイン
      description: 使用しているプラグインは何ですか？
    validations:
      required: false

  - type: input
    id: opencode-version
    attributes:
      label: OpenCode バージョン
      description: どのバージョンの OpenCode を使用していますか？
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: 再現手順
      description: この問題をどのように再現できますか？
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    id: screenshot-or-link
    attributes:
      label: スクリーンショット / シェアリンク
      description: "`/share` を実行してシェアリンクを取得するか、スクリーンショットを貼り付けてください"
      placeholder: リンクを貼り付けか、スクリーンショットをドラッグ＆ドロップ
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: オペレーティングシステム
      description: どのOSを使用していますか？
      placeholder: 例：macOS 26.0.1, Ubuntu 22.04, Windows 11
    validations:
      required: false

  - type: input
    id: terminal
    attributes:
      label: ターミナル
      description: どのターミナルを使用していますか？
      placeholder: 例：iTerm2, Ghostty, Alacritty, Windows Terminal
    validations:
      required: false
