name: 🚀 機能リクエスト
description: アイデア、機能、強化を提案する
labels: [discussion]
title: "[FEATURE]:"

body:
  - type: checkboxes
    id: verified
    attributes:
      label: この機能は以前に提案されていません。
      options:
        - label: この機能を提案する前に、既に提案されていないことを確認しました。
          required: true

  - type: textarea
    attributes:
      label: 要望する機能・強化を説明してください
      description: 何を変更・追加したいですか？その利点は何ですか？詳細に記載してもらえるほど、リクエストを適切に理解できます。
    validations:
      required: true
