import { expect, test } from "bun:test"

test("README documents the local WebSocket gateway contract without credential values", async () => {
  const source = await Bun.file("README.md").text()
  const packageJSON = await Bun.file("package.json").json()

  expect(source).toContain("bun run start")
  expect(source).toContain("im.message.receive_v1")
  expect(source).toContain("单聊")
  expect(source).toContain("群聊")
  expect(source).toContain("@机器人")
  expect(source).toContain("发送消息")
  expect(source).toContain("WebSocket")
  expect(source).toContain("不需要公网回调")
  expect(source).toContain("DeepSeek")
  expect(source).toContain("FEISHU_DATA_DIRECTORY")
  expect(source).toContain("FEISHU_MYSQL_PASSWORD_FILE")
  expect(source).toContain("FEISHU_PREFLIGHT_ONLY")
  expect(source).toContain("bun run test:mysql-contract")
  expect(source).toContain("standard-product:preview")
  expect(source).toContain("standard-product:apply")
  expect(source).toContain("standard-product:validate")
  expect(source).toContain("standard-product:rollback")
  expect(source).toContain("Storage")
  expect(source).toContain("--expected-sha256")
  expect(source).toContain("--expected-row-count")
  expect(source).toContain("--expected-matched")
  expect(source).toContain("--expected-missing")
  expect(source).toContain("--expected-ambiguous")
  expect(source).toContain("--expected-active-run")
  expect(source).toContain("供应商只使用标准表中的“产地”")
  expect(source).not.toContain("最近一张已审核")
  expect(packageJSON.scripts["standard-product:preview"]).toContain("--mode Preview")
  expect(packageJSON.scripts["standard-product:apply"]).toContain("--mode Apply")
  expect(packageJSON.scripts["standard-product:validate"]).toContain("--mode Validate")
  expect(packageJSON.scripts["standard-product:rollback"]).toContain("--mode Rollback")
  expect(source).toContain("不使用 SQL Server 回退")
  expect(source).toContain("不包含内部商品编码")
  expect(source).toContain("6001ZZ（清油）（12×28×8）（货架号：B-11-13）上海涂众轴承库存200，备注：xxx")
  expect(source).toContain("readonly: true")
  expect(source).toContain("gateway_event")
  expect(source).not.toContain("secret-canary")
  expect(source).not.toContain("cli_test")
})
