// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DEFAULT_PLATFORMS: typeof import('/home/jordan/github/eidorail/packages/extension/utils/shared').DEFAULT_PLATFORMS
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const PLATFORMS: typeof import('/home/jordan/github/eidorail/packages/extension/utils/platforms').PLATFORMS
  const PLATFORM_ICONS: typeof import('/home/jordan/github/eidorail/packages/extension/utils/shared').PLATFORM_ICONS
  const PRESET_PLATFORMS: typeof import('/home/jordan/github/eidorail/packages/extension/utils/shared').PRESET_PLATFORMS
  const SettingsPanel: typeof import('/home/jordan/github/eidorail/packages/extension/components/SettingsPanel').SettingsPanel
  const browser: typeof import('wxt/browser').browser
  const canCaptureUrl: typeof import('/home/jordan/github/eidorail/packages/extension/utils/browser-context').canCaptureUrl
  const captureScreenshot: typeof import('/home/jordan/github/eidorail/packages/extension/utils/browser-context').captureScreenshot
  const checkOpenCodeStatus: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').checkOpenCodeStatus
  const checkUrl: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').checkUrl
  const copyToClipboard: typeof import('/home/jordan/github/eidorail/packages/extension/utils/terminal-launcher').copyToClipboard
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const detectPlatform: typeof import('/home/jordan/github/eidorail/packages/extension/utils/terminal-launcher').detectPlatform
  const elementToMarkdown: typeof import('/home/jordan/github/eidorail/packages/extension/utils/markdown-converter').elementToMarkdown
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const formatCapturedContent: typeof import('/home/jordan/github/eidorail/packages/extension/utils/markdown-converter').formatCapturedContent
  const formatScreenshot: typeof import('/home/jordan/github/eidorail/packages/extension/utils/markdown-converter').formatScreenshot
  const getActiveTab: typeof import('/home/jordan/github/eidorail/packages/extension/utils/browser-context').getActiveTab
  const getBackgroundStartCommand: typeof import('/home/jordan/github/eidorail/packages/extension/utils/terminal-launcher').getBackgroundStartCommand
  const getConnectionMode: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').getConnectionMode
  const getConversationId: typeof import('/home/jordan/github/eidorail/packages/extension/utils/platforms').getConversationId
  const getCurrentWindowTabs: typeof import('/home/jordan/github/eidorail/packages/extension/utils/browser-context').getCurrentWindowTabs
  const getExportablePlatforms: typeof import('/home/jordan/github/eidorail/packages/extension/utils/platforms').getExportablePlatforms
  const getIcon: typeof import('/home/jordan/github/eidorail/packages/extension/utils/shared').getIcon
  const getOpenCodePort: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').getOpenCodePort
  const getOpenCodeUrl: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').getOpenCodeUrl
  const getPlatformConfig: typeof import('/home/jordan/github/eidorail/packages/extension/utils/platforms').getPlatformConfig
  const getRemoteUrl: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').getRemoteUrl
  const getStartCommand: typeof import('/home/jordan/github/eidorail/packages/extension/utils/terminal-launcher').getStartCommand
  const getWorkspaceDirectory: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').getWorkspaceDirectory
  const htmlToMarkdown: typeof import('/home/jordan/github/eidorail/packages/extension/utils/markdown-converter').htmlToMarkdown
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isConversationPage: typeof import('/home/jordan/github/eidorail/packages/extension/utils/platforms').isConversationPage
  const isExportSupported: typeof import('/home/jordan/github/eidorail/packages/extension/utils/platforms').isExportSupported
  const isWorkspaceEnabled: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').isWorkspaceEnabled
  const launchOpenCodeInTerminal: typeof import('/home/jordan/github/eidorail/packages/extension/utils/terminal-launcher').launchOpenCodeInTerminal
  const launchWindowsTerminal: typeof import('/home/jordan/github/eidorail/packages/extension/utils/terminal-launcher').launchWindowsTerminal
  const loadPlatforms: typeof import('/home/jordan/github/eidorail/packages/extension/utils/shared').loadPlatforms
  const manualPortScan: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').manualPortScan
  const retryConnection: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').retryConnection
  const saveOpenCodePort: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').saveOpenCodePort
  const savePlatformsToStorage: typeof import('/home/jordan/github/eidorail/packages/extension/utils/shared').savePlatformsToStorage
  const setConnectionMode: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').setConnectionMode
  const setRemoteUrl: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').setRemoteUrl
  const setWorkspaceDirectory: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').setWorkspaceDirectory
  const setWorkspaceEnabled: typeof import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status').setWorkspaceEnabled
  const storage: typeof import('wxt/utils/storage').storage
  const turndownService: typeof import('/home/jordan/github/eidorail/packages/extension/utils/markdown-converter').turndownService
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { TabInfo, TabGroup, GroupedTabs, CaptureMessageType, CaptureMessage, CaptureResponse } from '/home/jordan/github/eidorail/packages/extension/utils/browser-context'
  import('/home/jordan/github/eidorail/packages/extension/utils/browser-context')
  // @ts-ignore
  export type { ConnectionStatus, ConnectionMode } from '/home/jordan/github/eidorail/packages/extension/utils/opencode-status'
  import('/home/jordan/github/eidorail/packages/extension/utils/opencode-status')
  // @ts-ignore
  export type { PlatformConfig } from '/home/jordan/github/eidorail/packages/extension/utils/platforms'
  import('/home/jordan/github/eidorail/packages/extension/utils/platforms')
  // @ts-ignore
  export type { OpenCodeStatus } from '/home/jordan/github/eidorail/packages/extension/utils/shared'
  import('/home/jordan/github/eidorail/packages/extension/utils/shared')
  // @ts-ignore
  export type { Platform } from '/home/jordan/github/eidorail/packages/extension/utils/terminal-launcher'
  import('/home/jordan/github/eidorail/packages/extension/utils/terminal-launcher')
}
