// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/claude-iframe-fix.js"
    | "/content-scripts/conversation-export.js"
    | "/content-scripts/opencode-compact.js"
    | "/content-scripts/page-context.js"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/icon-48.png"
    | "/iframe-rules.json"
    | "/options.html"
    | "/sidepanel.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
