import path from "node:path"

const packages = path.resolve(import.meta.dirname, "../..")
const imports = new Set([
  "solid-js",
  "solid-js/store",
  "solid-js/web",
  "@tanstack/solid-query",
  "effect",
  "@opencode/plugin/desktop",
  "@opencode/plugin/desktop/solid",
  "@opencode/plugin/desktop/manager",
  "@opencode/schema/rpc",
  "@opencode/client",
  "@opencode/util/encode",
  "@opencode/util/path",
])
for (const name of ["ui", "session-ui"]) {
  const directory = path.join(packages, name)
  const manifest: { name: string; exports: Record<string, string> } = await Bun.file(
    path.join(directory, "package.json"),
  ).json()
  for (const [key, target] of Object.entries(manifest.exports)) {
    if (!/\.tsx?$/.test(target) || /storybook/.test(key)) continue
    if (!key.includes("*")) {
      imports.add(key === "." ? manifest.name : manifest.name + key.slice(1))
      continue
    }
    const [prefix, suffix] = target.split("*")
    for await (const file of new Bun.Glob(target.slice(2)).scan(directory)) {
      if (/(\.test\.|\.stories\.|\.story\.)/.test(file)) continue
      imports.add(
        manifest.name +
          key.slice(1).replace("*", ("./" + file.replaceAll("\\", "/")).slice(prefix.length, -suffix.length)),
      )
    }
  }
}
await Bun.write(
  path.join(packages, "app/src/extensions/modules.gen.ts"),
  `// Generated by script/generate-extension-modules.ts. Shared renderer modules only.\nexport const modules: Record<string, () => Promise<unknown>> = {\n${Array.from(
    imports,
  )
    .sort()
    .map((name) => `  ${JSON.stringify(name)}: () => import(${JSON.stringify(name)}),`)
    .join("\n")}\n}\n`,
)
