#!/usr/bin/env bash

# Parse command line arguments
minor=false
while [ "$#" -gt 0 ]; do
  case "$1" in
    --minor) minor=true; shift 1;;
    *) echo "Unknown parameter: $1"; exit 1;;
  esac
done

git fetch --force --tags
latest_tag=$(git tag --sort=version:refname | grep -E '^github-v[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
if [ -z "$latest_tag" ]; then
  base_tag=$(git tag --sort=version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
  if [ -z "$base_tag" ]; then
    echo "No tags found"
    exit 1
  fi
  latest_tag="github-$base_tag"
fi

echo "Latest tag: $latest_tag"

version=${latest_tag#github-v}
IFS='.' read -ra VERSION <<< "$version"

if [ "$minor" = true ]; then
  minor_number=${VERSION[1]}
  let "minor_number++"
  new_version="github-v${VERSION[0]}.$minor_number.0"
else
  patch_number=${VERSION[2]}
  let "patch_number++"
  new_version="github-v${VERSION[0]}.${VERSION[1]}.$patch_number"
fi

echo "New version: $new_version"

# Tag
git tag "$new_version"
git push --tags
