import { tool } from "@opencode-ai/plugin"
import { mkdirSync, writeFileSync, existsSync } from "fs"
import { join, isAbsolute } from "path"

/**
 * scaffold_design: generates a professional, token-driven CSS foundation
 * (OKLCH palette + fluid type scale + spacing/radii/shadow/motion tokens +
 * a modern reset and sensible base styles). The point is to give any project
 * a non-generic design system to build on, instead of ad-hoc magic values.
 */

function clampLine(minRem: number, maxRem: number, minVw = 22, maxVw = 80): string {
  // Build a clamp() that scales font-size between two viewport widths.
  const slope = (maxRem - minRem) / (maxVw - minVw)
  const yAxis = minRem - slope * minVw
  const pref = `${yAxis.toFixed(3)}rem + ${(slope * 100).toFixed(3)}vw`
  return `clamp(${minRem}rem, ${pref}, ${maxRem}rem)`
}

function tokensCss(hue: number, chroma: number): string {
  const c = chroma
  const lines: string[] = []
  lines.push("/* Design tokens Ã¢â‚¬â€ single source of truth. Generated by scaffold_design. */")
  lines.push(":root {")
  lines.push("  color-scheme: light dark;")
  lines.push("")
  lines.push("  /* --- Accent (OKLCH: lightness chroma hue) --- */")
  lines.push(`  --accent-h: ${hue};`)
  lines.push(`  --accent-c: ${c};`)
  for (const l of [20, 30, 40, 50, 60, 70, 80, 90, 95]) {
    const cc = (c * Math.min(1, (100 - Math.abs(l - 60)) / 60 + 0.4)).toFixed(3)
    lines.push(`  --accent-${l}: oklch(${l}% ${cc} var(--accent-h));`)
  }
  lines.push("")
  lines.push("  /* --- Neutrals: slightly tinted toward the accent hue (not pure gray) --- */")
  const nC = 0.006
  for (const l of [10, 15, 20, 30, 40, 50, 60, 70, 80, 90, 95, 98, 100]) {
    lines.push(`  --neutral-${l}: oklch(${l}% ${nC} var(--accent-h));`)
  }
  lines.push("")
  lines.push("  /* --- Semantic colors (light) --- */")
  lines.push("  --color-bg: var(--neutral-100);")
  lines.push("  --color-surface: var(--neutral-98);")
  lines.push("  --color-surface-raised: var(--neutral-95);")
  lines.push("  --color-border: var(--neutral-90);")
  lines.push("  --color-text: var(--neutral-15);")
  lines.push("  --color-text-muted: var(--neutral-40);")
  lines.push("  --color-primary: var(--accent-50);")
  lines.push("  --color-primary-hover: color-mix(in oklch, var(--color-primary), black 12%);")
  lines.push("  --color-primary-text: var(--neutral-100);")
  lines.push("  --color-focus: var(--accent-60);")
  lines.push("")
  lines.push("  /* --- Fluid type scale (ratio ~1.25) --- */")
  lines.push(`  --text-xs: ${clampLine(0.75, 0.8)};`)
  lines.push(`  --text-sm: ${clampLine(0.875, 0.95)};`)
  lines.push(`  --text-base: ${clampLine(1, 1.125)};`)
  lines.push(`  --text-lg: ${clampLine(1.125, 1.375)};`)
  lines.push(`  --text-xl: ${clampLine(1.375, 1.75)};`)
  lines.push(`  --text-2xl: ${clampLine(1.75, 2.4)};`)
  lines.push(`  --text-3xl: ${clampLine(2.2, 3.4)};`)
  lines.push(`  --text-4xl: ${clampLine(2.8, 4.6)};`)
  lines.push("")
  lines.push("  /* --- Type system --- */")
  lines.push("  --font-sans: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;")
  lines.push("  --font-mono: ui-monospace, 'Cascadia Code', 'JetBrains Mono', 'Fira Code', Menlo, Consolas, monospace;")
  lines.push("  --leading-tight: 1.15;")
  lines.push("  --leading-snug: 1.3;")
  lines.push("  --leading-body: 1.6;")
  lines.push("  --tracking-tight: -0.02em;")
  lines.push("  --measure: 65ch;")
  lines.push("")
  lines.push("  /* --- Spacing scale (base 4px in rem) --- */")
  const sp: Record<string, string> = { "1": "0.25", "2": "0.5", "3": "0.75", "4": "1", "5": "1.5", "6": "2", "7": "3", "8": "4", "9": "6", "10": "8" }
  for (const [k, v] of Object.entries(sp)) lines.push(`  --space-${k}: ${v}rem;`)
  lines.push("")
  lines.push("  /* --- Radii --- */")
  lines.push("  --radius-sm: 0.375rem;")
  lines.push("  --radius-md: 0.625rem;")
  lines.push("  --radius-lg: 1rem;")
  lines.push("  --radius-full: 9999px;")
  lines.push("")
  lines.push("  /* --- Elevation (soft, multi-layer) --- */")
  lines.push("  --shadow-sm: 0 1px 2px oklch(0% 0 0 / 0.06), 0 1px 1px oklch(0% 0 0 / 0.04);")
  lines.push("  --shadow-md: 0 4px 12px oklch(0% 0 0 / 0.08), 0 2px 4px oklch(0% 0 0 / 0.05);")
  lines.push("  --shadow-lg: 0 12px 32px oklch(0% 0 0 / 0.12), 0 4px 8px oklch(0% 0 0 / 0.06);")
  lines.push("")
  lines.push("  /* --- Motion --- */")
  lines.push("  --ease-out: cubic-bezier(0.22, 1, 0.36, 1);")
  lines.push("  --dur-fast: 130ms;")
  lines.push("  --dur-base: 200ms;")
  lines.push("")
  lines.push("  /* --- Layout --- */")
  lines.push("  --container: 72rem;")
  lines.push("  --container-narrow: 44rem;")
  lines.push("}")
  lines.push("")
  lines.push("/* --- Dark theme --- */")
  lines.push("@media (prefers-color-scheme: dark) {")
  lines.push("  :root {")
  lines.push("    --color-bg: var(--neutral-10);")
  lines.push("    --color-surface: var(--neutral-15);")
  lines.push("    --color-surface-raised: var(--neutral-20);")
  lines.push("    --color-border: var(--neutral-30);")
  lines.push("    --color-text: var(--neutral-95);")
  lines.push("    --color-text-muted: var(--neutral-60);")
  lines.push("    --color-primary: var(--accent-70);")
  lines.push("    --color-primary-hover: color-mix(in oklch, var(--color-primary), white 12%);")
  lines.push("    --color-primary-text: var(--neutral-10);")
  lines.push("  }")
  lines.push("}")
  lines.push("")
  return lines.join("\n")
}

function baseCss(): string {
  return [
    "/* Modern reset + base styles built on tokens.css. */",
    "@layer reset, base, components, utilities;",
    "",
    "@layer reset {",
    "  *, *::before, *::after { box-sizing: border-box; }",
    "  * { margin: 0; }",
    "  html { -webkit-text-size-adjust: 100%; scroll-behavior: smooth; }",
    "  body { min-height: 100dvh; -webkit-font-smoothing: antialiased; }",
    "  img, picture, video, canvas, svg { display: block; max-width: 100%; }",
    "  input, button, textarea, select { font: inherit; color: inherit; }",
    "  p, h1, h2, h3, h4, h5, h6 { overflow-wrap: break-word; }",
    "  ul[role='list'], ol[role='list'] { list-style: none; padding: 0; }",
    "  @media (prefers-reduced-motion: reduce) {",
    "    *, *::before, *::after { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; scroll-behavior: auto !important; }",
    "  }",
    "}",
    "",
    "@layer base {",
    "  body {",
    "    font-family: var(--font-sans);",
    "    font-size: var(--text-base);",
    "    line-height: var(--leading-body);",
    "    color: var(--color-text);",
    "    background: var(--color-bg);",
    "  }",
    "  h1, h2, h3, h4 { line-height: var(--leading-tight); letter-spacing: var(--tracking-tight); text-wrap: balance; }",
    "  h1 { font-size: var(--text-4xl); }",
    "  h2 { font-size: var(--text-3xl); }",
    "  h3 { font-size: var(--text-2xl); }",
    "  h4 { font-size: var(--text-xl); }",
    "  p { text-wrap: pretty; max-width: var(--measure); }",
    "  a { color: var(--color-primary); text-underline-offset: 0.2em; }",
    "  :focus-visible { outline: 2px solid var(--color-focus); outline-offset: 2px; border-radius: var(--radius-sm); }",
    "  ::selection { background: var(--accent-90); }",
    "}",
    "",
    "@layer components {",
    "  .container { width: 100%; max-width: var(--container); margin-inline: auto; padding-inline: var(--space-5); }",
    "  .stack > * + * { margin-block-start: var(--space-5); }",
    "",
    "  .btn {",
    "    display: inline-flex; align-items: center; justify-content: center; gap: var(--space-2);",
    "    padding: var(--space-3) var(--space-5); border-radius: var(--radius-md);",
    "    font-weight: 600; font-size: var(--text-sm); line-height: 1; cursor: pointer;",
    "    border: 1px solid transparent; transition: background var(--dur-fast) var(--ease-out), transform var(--dur-fast) var(--ease-out);",
    "  }",
    "  .btn:active { transform: translateY(1px); }",
    "  .btn-primary { background: var(--color-primary); color: var(--color-primary-text); }",
    "  .btn-primary:hover { background: var(--color-primary-hover); }",
    "  .btn-secondary { background: var(--color-surface-raised); color: var(--color-text); border-color: var(--color-border); }",
    "  .btn-secondary:hover { background: color-mix(in oklch, var(--color-surface-raised), var(--color-text) 6%); }",
    "  .btn-ghost { background: transparent; color: var(--color-text); }",
    "  .btn-ghost:hover { background: var(--color-surface); }",
    "  .btn:disabled { opacity: 0.55; cursor: not-allowed; }",
    "",
    "  .card {",
    "    background: var(--color-surface); border: 1px solid var(--color-border);",
    "    border-radius: var(--radius-lg); padding: var(--space-6); box-shadow: var(--shadow-sm);",
    "  }",
    "}",
    "",
  ].join("\n")
}

export default tool({
  description: `Scaffold a professional, token-driven CSS foundation into a project.

Generates a 'tokens.css' (OKLCH color system with light/dark, fluid type scale via clamp(),
spacing/radii/shadow/motion tokens, layout widths) and a 'base.css' (modern reset + base
typography + button/card components + accessible focus). Use this at the START of any
frontend/UI task so styling is built on a real design system instead of generic magic values.

After running, @import or link tokens.css before base.css, then build components using the
CSS variables (var(--color-primary), var(--space-5), var(--text-2xl), etc.).`,
  args: {
    directory: tool.schema.string().describe("Absolute or project-relative directory where the CSS files will be written (e.g. 'src/styles' or 'public/css')"),
    accentHue: tool.schema.number().describe("OKLCH hue 0-360 for the brand accent. Examples: 25 warm/orange, 150 green, 200 cyan, 260 indigo, 320 magenta. Avoid the generic default blue-violet unless the brand calls for it.").optional(),
    chroma: tool.schema.number().describe("Accent chroma/saturation 0.05-0.25 (default 0.15). Lower = muted/elegant, higher = vivid.").optional(),
    includeBase: tool.schema.boolean().describe("Also write base.css with reset + base styles + components (default true).").optional(),
  },
  async execute(args, context) {
    const hue = Math.max(0, Math.min(360, args.accentHue ?? 255))
    const chroma = Math.max(0.04, Math.min(0.25, args.chroma ?? 0.15))
    const includeBase = args.includeBase ?? true

    const root = context?.directory ?? process.cwd()
    const baseDir = isAbsolute(args.directory) ? args.directory : join(root, args.directory)
    try {
      mkdirSync(baseDir, { recursive: true })
    } catch (e) {
      return `Failed to create directory ${baseDir}: ${String(e)}`
    }

    const written: string[] = []
    const tokensPath = join(baseDir, "tokens.css")
    writeFileSync(tokensPath, tokensCss(hue, chroma), "utf8")
    written.push(tokensPath)

    if (includeBase) {
      const basePath = join(baseDir, "base.css")
      const header = `/* Import tokens first. */\n@import "./tokens.css";\n\n`
      writeFileSync(basePath, header + baseCss(), "utf8")
      written.push(basePath)
    }

    return [
      `Created a professional design-token foundation (accent hue ${hue}, chroma ${chroma}):`,
      ...written.map((w) => `  - ${w}`),
      "",
      "Next steps:",
      includeBase
        ? "  1. Link/import base.css in your entry (it already @imports tokens.css)."
        : "  1. Link/import tokens.css in your entry.",
      "  2. Build components using the CSS variables: var(--color-primary), var(--space-5), var(--text-2xl), var(--radius-lg), var(--shadow-md).",
      "  3. Derive state colors with color-mix() on tokens; do not introduce new hex values.",
      "  4. Keep the palette restrained and pass the frontend-design anti-generic checklist.",
    ].join("\n")
  },
})