# -*- coding: utf-8 -*-
"""Import native-speaker corrections and write script/be_overrides.py.

Accepts either:
  - be-translation-review.csv   (edited by the reviewer; column "belarusian")
  - be-edits.json               (downloaded from the review HTML page)

Only values that differ from the current generated be.ts are kept. The result
is written to script/be_overrides.py and is applied with highest priority by
be-locale-gen.py on the next regeneration.

Usage:
    python script/be-import.py [path-to-csv-or-json]
"""
import csv
import io
import json
import os
import re
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

DOMAIN_DIR = {
    "app": "packages/app/src/i18n",
    "ui": "packages/ui/src/i18n",
    "desktop": "packages/desktop/src/renderer/i18n",
    "console": "packages/console/app/src/i18n",
}

PATTERN = re.compile(r'^\s*"([^"]+)":\s*("(?:[^"\\]|\\.)*"),?\s*$', re.MULTILINE)


def unescape(raw):
    inner = raw[1:-1]
    out = []
    i = 0
    while i < len(inner):
        ch = inner[i]
        if ch == "\\" and i + 1 < len(inner):
            n = inner[i + 1]
            out.append({"n": "\n", "t": "\t", "r": "\r", '"': '"', "\\": "\\"}.get(n, n))
            i += 2
        else:
            out.append(ch)
            i += 1
    return "".join(out)


def parse_be(domain):
    path = os.path.join(ROOT, DOMAIN_DIR[domain], "be.ts")
    if not os.path.exists(path):
        return {}
    src = open(path, encoding="utf-8").read()
    return {m.group(1): unescape(m.group(2)) for m in PATTERN.finditer(src)}


def main(argv):
    src = argv[1] if len(argv) > 1 else None
    rows = []
    if src and src.endswith(".json"):
        rows = json.load(open(src, encoding="utf-8"))
    else:
        path = src or os.path.join(ROOT, "be-translation-review.csv")
        if not os.path.exists(path):
            path = os.path.join(HERE, "..", "be-translation-review.csv")
        with open(path, encoding="utf-8-sig", newline="") as fh:
            rows = list(csv.DictReader(fh))

    current = {d: parse_be(d) for d in DOMAIN_DIR}
    overrides = {}
    changed = []

    for r in rows:
        domain = (r.get("domain") or "app").strip()
        key = (r.get("key") or "").strip()
        be = (r.get("belarusian") or r.get("be") or "").strip()
        if not key or not be:
            continue
        if domain not in DOMAIN_DIR:
            domain = "app"
        old = current.get(domain, {}).get(key)
        if old is None:
            overrides[key] = be
            changed.append((domain, key, old, be))
        elif old.strip() != be.strip():
            # real correction (ignore whitespace-only differences)
            overrides[key] = be.strip()
            changed.append((domain, key, old, be.strip()))

    out = os.path.join(HERE, "be_overrides.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("# -*- coding: utf-8 -*-\n")
        fh.write('"""Native-speaker corrections (auto-generated by be-import.py).\\n')
        fh.write("Applied with highest priority by be-locale-gen.py.""" + '"""\n\n')
        fh.write("OVERRIDES = {\n")
        for k, v in overrides.items():
            fh.write('    %r: %r,\n' % (k, v))
        fh.write("}\n")

    print("corrections imported:", len(overrides))
    for domain, key, old, new in changed[:30]:
        print("  [%s] %s\n      - %s\n      + %s" % (domain, key, old, new))
    if len(changed) > 30:
        print("  ... and %d more" % (len(changed) - 30))
    print("wrote:", out)
    print("next: python script/be-locale-gen.py  &&  rebuild")


if __name__ == "__main__":
    main(sys.argv)
