# -*- coding: utf-8 -*-
"""Proofread corrections (models A+B, merged)."""

OVERRIDES = {
    'app.meta.description': 'OpenCode — Адкрытакодавы агент для праграмавання.',
    'bench.detail.labels.weight': 'Вага',
    'black.terms.5': 'Падпіскі прызначаныя для асобных карыстальнікаў, звяжыцеся з Enterprise для каманд',
    'black.terms.6': 'Ліміты могуць быць зменены, а тарыфныя планы могуць быць спынены ў будучыні',
    'common.videoUnsupported': 'Ваш браўзер не падтрымлівае відэатэг.',
    'context.stats.sessionCreated': 'Сеанс створаны',
    'desktop.menu.settings': 'Налады',
    'desktop.recovery.action.keepWaiting': 'Працягваць чаканне',
    'desktop.updater.dialog.checkFailed.title': 'Памылка абнаўлення',
    'desktop.updater.downloaded.prompt': 'Версія {{version}} OpenCode загружана. Хочаце ўсталяваць яе і перазапусціць?',
    'desktop.wsl.error.updateVersion': 'Абнаўленне OpenCode завершана, але {{distro}} па-ранейшаму паведамляе версію {{installed}}; чакалася {{expected}}',
    'dialog.mcp.description': '{{enabled}} з {{total}} уключаны',
    'dialog.server.description': 'Пераключыце сервер OpenCode, да якого падключаецца гэтая праграма.',
    'dialog.server.empty': 'Пакуль няма сервераў',
    'dialog.usageExceeded.accountRateLimit.description': 'Ліміт выкарыстання дасягнуты. Каб працягнуць выкарыстоўваць гэтую мадэль зараз, уключыце выкарыстанне з вашага даступнага балансу.',
    'download.faq.a3.beforeLocal': 'Не абавязкова, але хутчэй за ўсё. Вам спатрэбіцца падпіска на AI, калі вы хочаце падключыць OpenCode да платнага правайдара, хоць вы можаце працаваць з',
    'download.faq.a5.p2.beforeZen': 'Любыя дадатковыя выдаткі будуць звязаныя з вашай падпіскай на правайдара мадэлі. Хоць OpenCode працуе з любым правайдарам мадэлей, мы рэкамендуем выкарыстоўваць',
    'enterprise.form.error.invalidEmailFormat': 'Няправільны фармат email.',
    'enterprise.form.phone.label': 'Нумар тэлефона',
    'error.apiKeyRequired': 'Патрабуецца API-ключ',
    'error.page.description': 'Адбылася памылка при загрузцы праграмы.',
    'error.reloadAmountMin': 'Сума папаўнення павінна быць не меншай за ${{amount}}',
    'error.reloadTriggerMin': 'Парог балансу павінен быць не меншы за ${{amount}}',
    'go.faq.a2': 'Go ўключае мадэлі, пералічаныя ніжэй, са шчодрымі лімітамі і надзейным доступам.',
    'go.faq.a9': 'Бясплатныя мадэлі ўключаюць Big Pickle плюс прамацыйныя мадэлі, даступныя ў дадзены момант, з квотай 200 запытаў/дзень. Go прапануе адабраную лінейку мадэляў з больш высокімі квотамі запытаў, якія прымяняюцца ў коўзных акенцах (5-гадзінных, тыднёвых і месячных), прыблізна эквівалентных базавым лімітам $12 за 5 гадзін, $30 за тыдзень і $60 за месяц; ліміты для канкрэтных мадэляў могуць адрознівацца (фактычная колькасць запытаў залежыць ад мадэлі і выкарыстання).',
    'go.hero.body': 'Go прыносіць агентнае кадаванне праграмістам па ўсім свеце. Прапануе шчодрыя ліміты і надзейны доступ да найбольш магутных мадэляў з адкрытым зыходным кодам, каб вы маглі ствараць з магутнымі агентамі без турбот аб кошце ці даступнасці.',
    'go.meta.description': 'Go каштуе $10/месяц, са шчодрымі лімітамі выкарыстання і надзейным доступам да вядучых мадэляў для кадавання.',
    'go.problem.item2': 'Шчодрыя ліміты і надзейны доступ',
    'home.faq.a3.p3': 'Хоць мы заахвочваем карыстальнікаў выкарыстоўваць Zen, OpenCode таксама pracуе з усімі папулярнымі правайдэрамі, такімі як OpenAI, Anthropic, xAI і г. д.',
    'home.faq.a8.p1': 'Так, OpenCode — цалкам адкрыты зыходны код. Зыходны код публічна даступны на',
    'home.hero.subtitle.a': 'Бясплатныя мадэлі ўключаныя, або падключыце любую мадэль ад любога правайдэра,',
    'home.hero.title': 'Адкрытакодавы агент на базе AI',
    'home.providerTip': 'Падключыцеся да больш чым 75 правайдэраў, каб выкарыстоўваць іншыя мадэлі, у тым ліку Claude, GPT, Gemini і інш.',
    'lsp.tooltip.none': 'Няма сервераў LSP',
    'model.input.audio': 'аудыя',
    'prompt.example.1': 'Выправіць TODO ў кодзе',
    'prompt.toast.pasteUnsupported.title': 'Непадтрыманае ўкладанне',
    'session.error.notFound.description': 'Гэтая укладка спасылаецца на сеанс, які больш не існуе на гэтым серверы.',
    'session.followupDock.summary.few': '{{count}} паведамленні ў чарзе',
    'session.followupDock.summary.many': '{{count}} паведамленняў у чарзе',
    'session.followupDock.summary.other': '{{count}} паведамлення ў чарзе',
    'session.header.open.fileManager': 'Файлавы менеджар',
    'session.question.pending.few': '{{count}} пытанні без адказу',
    'session.question.pending.other': '{{count}} пытання чакае',
    'session.revertDock.summary.other': '{{count}} адкочанага паведамлення',
    'session.share.copy.copied': 'Скапіявана',
    'session.share.copy.copyLink': 'Скапіяваць спасылку',
    'settings.agents.description': 'Наладкі агентаў будуць даступныя тут.',
    'settings.commands.description': 'Наладкі каманд будуць даступныя тут.',
    'settings.desktop.wsl.title': 'Інтэграцыя з WSL',
    'settings.general.notifications.permissions.description': 'Паказваць сістэмнае апавяшчэнне, калі патрабуецца дазвол',
    'settings.general.row.newInterface.description': 'Выкарыстоўваць новы макет укладак і галоўнай старонкі. Пераключайцеся паміж макетамі на працягу абмежаванага часу.',
    'settings.general.row.pinchZoom.description': 'Дазволіць жэсты шчыпка на трэкпадзе і Ctrl-пракрутку для маштабавання',
    'settings.general.row.releaseNotes.description': 'Паказваць усплыўныя вокны "Што новага" пасля абнаўленняў',
    'settings.general.row.shell.autoDefault': 'Аўта (па змоўчанні)',
    'settings.general.sounds.permissions.description': 'Прайграваць гук, калі патрабуецца дазвол',
    'settings.mcp.description': 'Наладкі MCP будуць даступныя для канфігурацыі тут.',
    'settings.models.description': 'Наладкі мадэляў будуць даступныя тут.',
    'settings.permissions.tool.todowrite.description': 'Абнаўленне спісу задач',
    'settings.permissions.tool.webfetch.description': 'Атрымаць змест з URL-адраса',
    'settings.providers.connected.environmentDescription': 'Падключана з вашых зменных асяроддзяў',
    'settings.providers.description': 'Наладкі правайдэраў будуць даступныя тут.',
    'toast.session.export.failed.description': 'Адбылася памылка пры экспарце сеансу',
    'toast.session.unshare.failed.description': 'Адбылася памылка пры адмене супольнага доступу да сеансу',
    'ui.basicTool.called': 'Выклікана `{{tool}}`',
    'ui.message.copied': 'Скапіявана',
    'ui.messagePart.context.list.few': '{{count}} спісы',
    'ui.messagePart.context.read.few': '{{count}} прачытанні',
    'ui.messagePart.context.read.many': '{{count}} прачытанняў',
    'ui.messagePart.context.search.few': '{{count}} пошукі',
    'ui.question.subtitle.answered': '{{count}} адказаў',
    'ui.sessionReview.title.lastTurn': 'Змены апошняга ходу',
    'ui.sessionReviewV2.empty.changes.title': 'Пакуль няма змен у файлах',
    'ui.sessionTurn.diffs.changed.few': '{{count}} змененыя файлы',
    'ui.sessionTurn.diffs.changed.other': '{{count}} змененых файлаў',
    'ui.sessionTurn.diffs.more': '+ яшчэ {{count}} файлаў',
    'workspace.billing.enable': 'Уключыць білінг',
    'workspace.cost.subscriptionShort': 'падп.',
    'workspace.keys.empty': 'Стварыце API ключ OpenCode Gateway',
    'workspace.keys.subtitle': 'Кіруйце сваімі API ключамі для доступу да сэрвісаў OpenCode.',
    'workspace.lite.promo.footer': 'План распрацаваны ў першую чаргу для міжнародных карыстальнікаў і забяспечвае стабільны глабальны доступ. Цэны і ліміты выкарыстання могуць змяніцца па меры атрымання вопыту і водгукаў.',
    'workspace.lite.subscription.useBalance': 'Выкарыстоўвайце даступны баланс пасля дасягнення лімітаў выкарыстання',
    'workspace.monthlyLimit.noLimit': 'Ліміт выкарыстання не ўстаноўлены.',
    'workspace.monthlyLimit.set': 'Устанавіць',
    'workspace.monthlyLimit.setting': 'Устаноўка...',
    'workspace.monthlyLimit.subtitle': 'Устанавіце месячны ліміт выкарыстання для вашага ўліковага запісу.',
    'workspace.referral.reward.action.applied': 'Узнагарода прыменена',
    'workspace.referral.reward.source.applied': 'Узнагарода прыменена',
    'workspace.referral.reward.source.pendingInviter': 'Чакаем, пакуль яны падпішуцца',
    'workspace.referral.reward.status.applied': 'Узнагарода прыменена',
    'workspace.referral.rewards.empty': 'Пакуль няма рэферальных узнагарод.',
    'workspace.reload.disabled.after': 'Уключыце, каб аўтаматычна папаўняць баланс при нізкім узроўні.',
    'workspace.reload.enabled.state': 'ўключана',
    'workspace.reset.archived.many': '{{count}} сеансаў будзе архівавана.',
    'workspace.reset.archived.one': '1 сеанс будзе архіваваны.',
    'workspace.reset.note': 'Гэта скіне працоўную прастору да стану галіны па змоўчанні.',
    'workspace.settings.defaultName': 'Па змоўчанні',
    'wsl.onboarding.checkingOpencodeIn': 'Праверка OpenCode ў {{distro}}...',
    'wsl.onboarding.updatingOpencodeIn': 'Абнаўленне OpenCode ў {{distro}}...',
    'zen.api.error.goSubscriptionMonthlyLimitExceeded': 'Дасягнуты месячны ліміт выкарыстання. Абновіцца праз {{retryIn}}. Каб працягнуць выкарыстанне гэтай мадэлі зараз, уключыце выкарыстанне з вашага даступнага балансу: {{consoleGoUrl}}',
    'zen.api.error.goSubscriptionRollingLimitExceeded': 'Дасягнуты ліміт выкарыстання за 5 гадзін. Абновіцца праз {{retryIn}}. Каб працягнуць выкарыстанне гэтай мадэлі зараз, уключыце выкарыстанне з вашага даступнага балансу: {{consoleGoUrl}}',
    'zen.api.error.goSubscriptionWeeklyLimitExceeded': 'Дасягнуты тыднёвы ліміт выкарыстання. Абновіцца праз {{retryIn}}. Каб працягнуць выкарыстанне гэтай мадэлі зараз, уключыце выкарыстанне з вашага даступнага балансу: {{consoleGoUrl}}',
    'zen.api.error.insufficientBalance': 'Недастаткова сродкаў. Кіруйце вашым білінгам тут: {{billingUrl}}',
    'zen.faq.a2': 'Zen прапануе толькі мадэлі, якія былі спецыяльна пратэставаны і правераны бенчмаркамі для кодавых агентаў. Вы ж не выкарыстоўваеце нож для масла, каб разрэзаць стэйк. Не выкарыстоўвайце дрэнныя мадэлі для кадавання.',
    'zen.faq.a3': 'Zen не накіраваны на атрыманне прыбытку. Zen перадае вам выдаткі ад правайдэраў мадэляў. Чым вышэй выкарыстанне Zen, тым больш OpenCode можа дамовіцца наконт лепшых тарыфаў і перадаць іх вам.',
    'zen.faq.a4.p1.afterPricing': 'без ніякіх нацэнак, таму вы плаціце менавіта столькі, колькі бярэ пастаўшчык мадэлі.',
    'zen.faq.a7': 'Так, вы можаце адключыць біллінг у любы час і выкарыстаць астатні баланс.',
    'zen.problem.item3': 'Бенчмаркінг усіх камбінацый мадэляў-пастаўшчыкоў, якія мы рэкамендуем',
}
