# -*- coding: utf-8 -*-
"""Proofread corrections (model B, auto-generated)."""

OVERRIDES = {
    'desktop.recovery.action.keepWaiting': 'Працягваць чаканне',
    'prompt.example.1': 'Выправіць TODO ў кодзе',
    'prompt.toast.pasteUnsupported.title': 'Непадтрыманае ўкладанне',
    'dialog.mcp.description': '{{enabled}} з {{total}} уключаны',
    'wsl.onboarding.checkingOpencodeIn': 'Праверка OpenCode ў {{distro}}...',
    'wsl.onboarding.updatingOpencodeIn': 'Абнаўленне OpenCode ў {{distro}}...',
    'home.providerTip': 'Падключыцеся да больш чым 75 правайдэраў, каб выкарыстоўваць іншыя мадэлі, у тым ліку Claude, GPT, Gemini і інш.',
    'session.error.notFound.description': 'Гэтая укладка спасылаецца на сеанс, які больш не існуе на гэтым серверы.',
    'session.question.pending.other': '{{count}} пытання чакае',
    'session.followupDock.summary.other': '{{count}} паведамлення ў чарзе',
    'session.revertDock.summary.other': '{{count}} адкочанага паведамлення',
    'settings.desktop.wsl.title': 'Інтэграцыя з WSL',
    'settings.general.row.shell.autoDefault': 'Аўта (па змоўчанні)',
    'settings.general.row.newInterface.description': 'Выкарыстоўваць новы макет укладак і галоўнай старонкі. Пераключайцеся паміж макетамі на працягу абмежаванага часу.',
    'settings.general.row.pinchZoom.description': 'Дазволіць жэсты шчыпка на трэкпадзе і Ctrl-пракрутку для маштабавання',
    'settings.providers.description': 'Наладкі правайдэраў будуць даступныя тут.',
    'settings.models.description': 'Наладкі мадэляў будуць даступныя тут.',
    'settings.agents.description': 'Наладкі агентаў будуць даступныя тут.',
    'settings.commands.description': 'Наладкі каманд будуць даступныя тут.',
    'settings.mcp.description': 'Наладкі MCP будуць даступныя для канфігурацыі тут.',
    'settings.permissions.tool.todowrite.description': 'Абнаўленне спісу задач',
    'workspace.reset.archived.many': '{{count}} сеансаў будзе архівавана.',
    'workspace.reset.note': 'Гэта скіне працоўную прастору да стану галіны па змоўчанні.',
    'settings.providers.connected.environmentDescription': 'Падключана з вашых зменных асяроддзяў',
    'settings.general.row.releaseNotes.description': 'Паказваць усплыўныя вокны "Што новага" пасля абнаўленняў',
    'ui.sessionReview.title.lastTurn': 'Змены апошняга ходу',
    'ui.sessionTurn.diffs.more': '+ яшчэ {{count}} файлаў',
    'dialog.usageExceeded.accountRateLimit.description': 'Ліміт выкарыстання дасягнуты. Каб працягнуць выкарыстоўваць гэтую мадэль зараз, уключыце выкарыстанне з вашага даступнага балансу.',
    'ui.messagePart.context.read.few': '{{count}} прачытанні',
    'ui.messagePart.context.read.many': '{{count}} прачытанняў',
    'ui.question.subtitle.answered': '{{count}} адказаў',
    'ui.basicTool.called': 'Выклікана `{{tool}}`',
    'error.apiKeyRequired': 'Патрабуецца API-ключ',
    'error.reloadAmountMin': 'Сума папаўнення павінна быць не меншай за ${{amount}}',
    'error.reloadTriggerMin': 'Парог балансу павінен быць не меншы за ${{amount}}',
    'app.meta.description': 'OpenCode — Адкрытакодавы агент для праграмавання.',
    'home.hero.title': 'Адкрытакодавы агент на базе AI',
    'home.hero.subtitle.a': 'Бясплатныя мадэлі ўключаныя, або падключыце любую мадэль ад любога правайдэра,',
    'home.faq.a8.p1': 'Так, OpenCode — цалкам адкрыты зыходны код. Зыходны код публічна даступны на',
    'zen.faq.a2': 'Zen прапануе толькі мадэлі, якія былі спецыяльна пратэставаны і правераны бенчмаркамі для кодавых агентаў. Вы ж не выкарыстоўваеце нож для масла, каб разрэзаць стэйк. Не выкарыстоўвайце дрэнныя мадэлі для кадавання.',
    'zen.faq.a3': 'Zen не накіраваны на атрыманне прыбытку. Zen перадае вам выдаткі ад правайдэраў мадэляў. Чым вышэй выкарыстанне Zen, тым больш OpenCode можа дамовіцца наконт лепшых тарыфаў і перадаць іх вам.',
    'zen.faq.a4.p1.afterPricing': 'без ніякіх нацэнак, таму вы плаціце менавіта столькі, колькі бярэ пастаўшчык мадэлі.',
    'zen.problem.item3': 'Бенчмаркінг усіх камбінацый мадэляў-пастаўшчыкоў, якія мы рэкамендуем',
    'go.meta.description': 'Go каштуе $10/месяц, са шчодрымі лімітамі выкарыстання і надзейным доступам да вядучых мадэляў для кадавання.',
    'go.problem.item2': 'Шчодрыя ліміты і надзейны доступ',
    'go.faq.a2': 'Go ўключае мадэлі, пералічаныя ніжэй, са шчодрымі лімітамі і надзейным доступам.',
    'go.faq.a9': 'Бясплатныя мадэлі ўключаюць Big Pickle плюс прамацыйныя мадэлі, даступныя ў дадзены момант, з квотай 200 запытаў/дзень. Go прапануе адабраную лінейку мадэляў з больш высокімі квотамі запытаў, якія прымяняюцца ў коўзных акенцах (5-гадзінных, тыднёвых і месячных), прыблізна эквівалентных базавым лімітам $12 за 5 гадзін, $30 за тыдзень і $60 за месяц; ліміты для канкрэтных мадэляў могуць адрознівацца (фактычная колькасць запытаў залежыць ад мадэлі і выкарыстання).',
    'zen.api.error.goSubscriptionRollingLimitExceeded': 'Дасягнуты ліміт выкарыстання за 5 гадзін. Абновіцца праз {{retryIn}}. Каб працягнуць выкарыстанне гэтай мадэлі зараз, уключыце выкарыстанне з вашага даступнага балансу: {{consoleGoUrl}}',
    'zen.api.error.goSubscriptionWeeklyLimitExceeded': 'Дасягнуты тыднёвы ліміт выкарыстання. Абновіцца праз {{retryIn}}. Каб працягнуць выкарыстанне гэтай мадэлі зараз, уключыце выкарыстанне з вашага даступнага балансу: {{consoleGoUrl}}',
    'zen.api.error.goSubscriptionMonthlyLimitExceeded': 'Дасягнуты месячны ліміт выкарыстання. Абновіцца праз {{retryIn}}. Каб працягнуць выкарыстанне гэтай мадэлі зараз, уключыце выкарыстанне з вашага даступнага балансу: {{consoleGoUrl}}',
    'black.terms.5': 'Падпіскі прызначаныя для асобных карыстальнікаў, звяжыцеся з Enterprise для каманд',
    'black.terms.6': 'Ліміты могуць быць зменены, а тарыфныя планы могуць быць спынены ў будучыні',
    'workspace.settings.defaultName': 'Па змоўчанні',
    'workspace.monthlyLimit.subtitle': 'Устанавіце месячны ліміт выкарыстання для вашага ўліковага запісу.',
    'workspace.monthlyLimit.setting': 'Устаноўка...',
    'workspace.monthlyLimit.set': 'Устанавіць',
    'workspace.monthlyLimit.noLimit': 'Ліміт выкарыстання не ўстаноўлены.',
    'workspace.reload.enabled.state': 'ўключана',
    'workspace.lite.subscription.useBalance': 'Выкарыстоўвайце даступны баланс пасля дасягнення лімітаў выкарыстання',
    'workspace.lite.promo.footer': 'План распрацаваны ў першую чаргу для міжнародных карыстальнікаў і забяспечвае стабільны глабальны доступ. Цэны і ліміты выкарыстання могуць змяніцца па меры атрымання вопыту і водгукаў.',
    'workspace.referral.reward.action.applied': 'Узнагарода прыменена',
    'workspace.referral.reward.source.applied': 'Узнагарода прыменена',
    'workspace.referral.reward.status.applied': 'Узнагарода прыменена',
    'download.faq.a3.beforeLocal': 'Не абавязкова, але хутчэй за ўсё. Вам спатрэбіцца падпіска на AI, калі вы хочаце падключыць OpenCode да платнага правайдара, хоць вы можаце працаваць з',
    'download.faq.a5.p2.beforeZen': 'Любыя дадатковыя выдаткі будуць звязаныя з вашай падпіскай на правайдара мадэлі. Хоць OpenCode працуе з любым правайдарам мадэлей, мы рэкамендуем выкарыстоўваць',
    'enterprise.form.phone.label': 'Нумар тэлефона',
    'enterprise.form.error.invalidEmailFormat': 'Няправільны фармат email.',
}
