#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"

const modelsUrl = process.env.ATHENA_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const VERSION = process.env.ATHENA_VERSION || pkg.version
const CHANNEL = process.env.ATHENA_CHANNEL || "latest"

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const plugin = createSolidTransformPlugin()
const skipEmbedWebUi = true // Web UI is not included in standalone extraction

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "arm64",
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(localPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [plugin],
    // Patchright must be excluded from bundling — it has native deps
    // (chromium-bidi, electron) that can't be statically compiled.
    // It's lazy-imported at runtime via `await import("patchright")`.
    external: ["patchright", "patchright-core"],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/athena`,
      execArgv: [`--user-agent=athena/${VERSION}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      ATHENA_VERSION: `'${VERSION}'`,
      ATHENA_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      ATHENA_WORKER_PATH: workerPath,
      ATHENA_CHANNEL: `'${CHANNEL}'`,
      ATHENA_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  // Smoke test: only run if binary is for current platform
  if (item.os === process.platform && item.arch === process.arch && !item.abi) {
    const binaryPath = `dist/${name}/bin/athena`
    console.log(`Running smoke test: ${binaryPath} --version`)
    try {
      const versionOutput = await $`${binaryPath} --version`.text()
      console.log(`Smoke test passed: ${versionOutput.trim()}`)
    } catch (e) {
      console.error(`Smoke test failed for ${name}:`, e)
      process.exit(1)
    }
  }

  await $`rm -rf ./dist/${name}/bin/tui`

  // Bundle agent-browser binary for this platform
  const agentBrowserBinary = await bundleAgentBrowser(item.os, item.arch, `dist/${name}/bin`)
  if (agentBrowserBinary) {
    console.log(`  Bundled agent-browser for ${item.os}-${item.arch}`)
  } else {
    console.log(`  Warning: agent-browser not bundled for ${item.os}-${item.arch}`)
  }

  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: VERSION,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = VERSION
}

if (process.env.ATHENA_RELEASE) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${VERSION} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

/**
 * Bundle the agent-browser binary for a specific platform.
 * Tries to copy from node_modules first, then falls back to npx-based resolution.
 */
async function bundleAgentBrowser(os: string, arch: string, outDir: string): Promise<boolean> {
  const ext = os === "win32" ? ".exe" : ""
  const outPath = path.join(outDir, `agent-browser${ext}`)

  // Map our target naming to agent-browser's naming convention
  const platformMap: Record<string, string> = {
    darwin: "darwin",
    linux: "linux",
    win32: "win32",
  }
  const agentBrowserPlatform = platformMap[os]
  if (!agentBrowserPlatform) return false

  // Try to find agent-browser binary from node_modules
  const nmBin = path.join(dir, "node_modules", ".bin", `agent-browser${ext}`)
  try {
    if (fs.existsSync(nmBin)) {
      const realPath = fs.realpathSync(nmBin)
      fs.copyFileSync(realPath, outPath)
      if (os !== "win32") {
        fs.chmodSync(outPath, 0o755)
      }
      return true
    }
  } catch {}

  // Try to find in the agent-browser package directory
  const agentBrowserPkg = path.join(dir, "node_modules", "agent-browser")
  try {
    if (fs.existsSync(agentBrowserPkg)) {
      // Look for platform-specific binaries in the package
      const binDir = path.join(agentBrowserPkg, "bin")
      if (fs.existsSync(binDir)) {
        const candidates = [
          `agent-browser-${agentBrowserPlatform}-${arch}${ext}`,
          `agent-browser${ext}`,
        ]
        for (const candidate of candidates) {
          const candidatePath = path.join(binDir, candidate)
          if (fs.existsSync(candidatePath)) {
            fs.copyFileSync(candidatePath, outPath)
            if (os !== "win32") {
              fs.chmodSync(outPath, 0o755)
            }
            return true
          }
        }
      }
    }
  } catch {}

  // If building for current platform, try to find it in PATH
  if (os === process.platform && arch === process.arch) {
    try {
      const whichCmd = process.platform === "win32" ? "where" : "which"
      const result = await $`${whichCmd} agent-browser`.text()
      const binaryPath = result.trim().split("\n")[0]?.trim()
      if (binaryPath && fs.existsSync(binaryPath)) {
        fs.copyFileSync(binaryPath, outPath)
        if (os !== "win32") {
          fs.chmodSync(outPath, 0o755)
        }
        return true
      }
    } catch {}
  }

  return false
}

export { binaries }
