#!/usr/bin/env bun

// Baseline of test presence per workspace package.
//
// This is the "0% coverage" analog from the audit: before raising coverage we need to see, per
// package, whether tests exist at all. Fast and dependency-free (no full suite run) so it can be
// re-run anytime. Pass a package dir to additionally run `bun test --coverage` there.
//
//   bun run script/coverage-baseline.ts                 # scan all packages, write the report
//   bun run script/coverage-baseline.ts packages/core   # also run coverage for one package

import { Glob } from "bun"
import path from "node:path"

const root = process.cwd()
const OUTPUT = "docs/coverage-baseline.md"

const WORKSPACE_GLOBS = [
  "packages/*/package.json",
  "packages/console/*/package.json",
  "packages/stats/*/package.json",
  "packages/sdk/js/package.json",
  "packages/slack/package.json",
]

type Pkg = { name?: string; scripts?: Record<string, string> }
type Row = { name: string; dir: string; hasTestScript: boolean; testFiles: number }

async function packageDirs() {
  const dirs = new Set<string>()
  for (const pattern of WORKSPACE_GLOBS) {
    for await (const file of new Glob(pattern).scan({ cwd: root })) {
      if (file.includes("node_modules")) continue
      dirs.add(path.dirname(file))
    }
  }
  return [...dirs].sort()
}

async function countTestFiles(dir: string) {
  let count = 0
  for await (const file of new Glob("**/*.test.ts").scan({ cwd: path.join(root, dir) })) {
    if (file.includes("node_modules") || file.startsWith("dist/")) continue
    count++
  }
  return count
}

async function scan(): Promise<Row[]> {
  const rows: Row[] = []
  for (const dir of await packageDirs()) {
    const pkg = (await Bun.file(path.join(root, dir, "package.json")).json()) as Pkg
    rows.push({
      name: pkg.name ?? dir,
      dir,
      hasTestScript: Boolean(pkg.scripts?.test),
      testFiles: await countTestFiles(dir),
    })
  }
  return rows.sort((a, b) => a.testFiles - b.testFiles || a.name.localeCompare(b.name))
}

function render(rows: Row[]) {
  const withTests = rows.filter((r) => r.testFiles > 0).length
  const date = new Date().toISOString().split("T")[0]
  const header = [
    "# Test-presence baseline",
    "",
    `Generated by \`script/coverage-baseline.ts\` on ${date}.`,
    "",
    `**${withTests}/${rows.length}** workspace packages contain at least one \`*.test.ts\` file.`,
    "Packages with zero test files are the priority targets for the coverage track.",
    "",
    "> Tests run from package dirs (`do-not-run-tests-from-root`). Per-package coverage:",
    "> `cd <package> && bun test --coverage`.",
    "",
    "| Package | Path | `test` script | Test files |",
    "| --- | --- | :---: | ---: |",
  ]
  const body = rows.map((r) => `| ${r.name} | \`${r.dir}\` | ${r.hasTestScript ? "yes" : "—"} | ${r.testFiles} |`)
  return [...header, ...body, ""].join("\n")
}

async function runCoverage(dir: string) {
  console.log(`\nRunning coverage for ${dir} …`)
  const proc = Bun.spawn(["bun", "test", "--coverage"], {
    cwd: path.join(root, dir),
    stdout: "inherit",
    stderr: "inherit",
  })
  const code = await proc.exited
  if (code !== 0) console.warn(`coverage run for ${dir} exited with code ${code}`)
}

const rows = await scan()
await Bun.write(OUTPUT, render(rows))
console.log(`Wrote ${OUTPUT} — ${rows.filter((r) => r.testFiles > 0).length}/${rows.length} packages have tests.`)

const target = process.argv[2]
if (target) await runCoverage(target)
