#!/usr/bin/env bun

import { $ } from "bun"
import { createHash } from "node:crypto"
import fs from "node:fs/promises"
import path from "node:path"

const root = path.resolve(import.meta.dir, "..")
const dist = path.join(root, "packages", "opencode", "dist")
const out = path.join(dist, "securecode-release")
const setupSrc = path.join(root, "setup")
// One-shot installer (`curl ... | bash`). Uploaded to releases as `install`
// so the user-facing download URL is `.../releases/latest/download/install`.
// See https://github.com/acompany-develop/securecode/issues/82.
const installerSrc = path.join(root, "install-securecode")
// Aggregated third-party license bundle, generated by the THIRD-PARTY-LICENSES
// pipeline (refs https://github.com/acompany-develop/securecode/issues/162).
// When present at repo root we copy it into each platform archive so the
// distributed binary ships with full upstream attribution.
const thirdPartyLicensesSrc = path.join(root, "THIRD-PARTY-LICENSES.txt")
const repo = process.env.GH_REPO ?? process.env.GITHUB_REPOSITORY
const tag = process.env.SECURECODE_TAG ?? version()
const skip = process.env.SECURECODE_SKIP_UPLOAD === "1"

if (!skip && !repo) {
  throw new Error("GH_REPO or GITHUB_REPOSITORY is required")
}

await fs.rm(out, { recursive: true, force: true })
await fs.mkdir(out, { recursive: true })

const sums: string[] = []
for (const dir of await fs.readdir(dist, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue
  if (!dir.name.startsWith("opencode-")) continue

  const meta = path.join(dist, dir.name, "package.json")
  if (!(await exists(meta))) continue

  if (dir.name.includes("windows")) continue

  const src = await bin(path.join(dist, dir.name, "bin"))
  if (!src) continue

  // Archive / dir / binary names are kept lowercase to match the CLI's
  // own `scriptName("securecode")` and the documented user-facing command
  // `securecode run ...`. The pre-existing capitalised naming led to a
  // command-not-found on case-sensitive (Linux) filesystems when users
  // followed the README.txt instructions verbatim.
  const name = dir.name.replace(/^opencode-/, "securecode-")
  const ext = dir.name.includes("darwin") ? "zip" : "tar.gz"
  const tmp = path.join(out, name)
  // securecode = supervisor (bun compile 単独バイナリ)、securecode-bin = opencode 本体。
  // ユーザが `securecode` を叩くと supervisor が同じディレクトリの securecode-bin を
  // sandbox 内で spawn する (詳細は .specs/20260526_securecode-sandbox-phase0.md 参照)。
  const supervisorBin = path.join(tmp, "securecode")
  const innerBin = path.join(tmp, "securecode-bin")
  const arc = path.join(out, `${name}.${ext}`)

  await fs.rm(tmp, { recursive: true, force: true })
  await fs.mkdir(tmp, { recursive: true })

  // 1) opencode 本体を securecode-bin として配置
  await fs.copyFile(src, innerBin)
  await fs.chmod(innerBin, 0o755)

  // 2) supervisor を securecode として bun compile (platform クロスコンパイル)
  const platformSuffix = dir.name.replace(/^opencode-/, "")
  const bunTarget = `bun-${platformSuffix}`
  await $`bun build --compile --target=${bunTarget} script/securecode-supervisor.ts --outfile ${supervisorBin}`.cwd(root)
  await fs.chmod(supervisorBin, 0o755)

  await fs.copyFile(path.join(root, "LICENSE"), path.join(tmp, "LICENSE"))
  if (await exists(thirdPartyLicensesSrc)) {
    await fs.copyFile(thirdPartyLicensesSrc, path.join(tmp, "THIRD-PARTY-LICENSES.txt"))
  }
  await Bun.write(path.join(tmp, "README.txt"), note(name))
  await copySetup(setupSrc, path.join(tmp, "setup"))

  if (ext === "zip") {
    await $`zip -rq ${arc} .`.cwd(tmp)
  } else {
    await $`tar -czf ${arc} -C ${tmp} .`
  }

  sums.push(`${sum(await Bun.file(arc).bytes())}  ${path.basename(arc)}`)
}

if (sums.length === 0) {
  throw new Error("No CLI binaries found in packages/opencode/dist")
}

const sumfile = path.join(out, "securecode-sha256.txt")
await Bun.write(sumfile, sums.join("\n") + "\n")

// Bundle the one-shot installer alongside the platform archives so users can
// `curl -fsSL .../releases/latest/download/install | bash`. We rename
// install-securecode → install for the asset name so the URL matches what is
// documented in the install guide.
if (await exists(installerSrc)) {
  const installerDst = path.join(out, "install")
  await fs.copyFile(installerSrc, installerDst)
  await fs.chmod(installerDst, 0o755)
}

// Surface the aggregated third-party license bundle at the release top level so
// reviewers / legal can inspect it without downloading a platform archive.
if (await exists(thirdPartyLicensesSrc)) {
  await fs.copyFile(thirdPartyLicensesSrc, path.join(out, "THIRD-PARTY-LICENSES.txt"))
}

const files = (await fs.readdir(out))
  .filter(
    (x) =>
      x === "securecode-sha256.txt" ||
      x === "install" ||
      x === "THIRD-PARTY-LICENSES.txt" ||
      x.endsWith(".zip") ||
      x.endsWith(".tar.gz"),
  )
  .map((x) => path.join(out, x))
  .sort()

if (skip) {
  console.log("Prepared assets:")
  for (const file of files) console.log(path.basename(file))
  process.exit(0)
}

await $`gh release upload ${tag} ${files} --clobber --repo ${repo}`

function version() {
  const raw = process.env.OPENCODE_VERSION
  if (!raw) throw new Error("SECURECODE_TAG or OPENCODE_VERSION is required")
  return `v${raw}`
}

async function exists(file: string) {
  return fs
    .access(file)
    .then(() => true)
    .catch(() => false)
}

async function bin(dir: string) {
  const full = path.join(dir, "opencode")
  if (await exists(full)) return full
}

async function copySetup(src: string, dst: string) {
  if (!(await exists(src))) return
  await fs.cp(src, dst, { recursive: true })
  const installer = path.join(dst, "install.sh")
  if (await exists(installer)) await fs.chmod(installer, 0o755)
}

function sum(buf: Uint8Array) {
  return createHash("sha256").update(buf).digest("hex")
}

function note(name: string) {
  return [
    "Acompany SecureCode CLI",
    "",
    `Asset: ${name}`,
    "",
    "Quick start:",
    "  1. bash setup/install.sh",
    "  2. export SECURECODE_QWEN3_API_KEY=<Qwen3.6 API key issued by Acompany>",
    "  3. Run ./securecode run \"Hello\"",
    "",
    "What setup/install.sh does:",
    "  - seeds ~/.config/securecode/securecode.json (Acompany Qwen3.6 endpoint template)",
    "  - seeds ~/.config/securecode/tui.json (selects the bundled `securecode` theme)",
    "  - seeds ~/.config/securecode/themes/securecode.json (Acompany-branded TUI colors)",
    "  Existing files are preserved.",
    "",
    "Notes:",
    "  - securecode.json is the preferred config name; opencode.json is also accepted.",
    "  - Branding (SecureCode wordmark / sidebar badge) ships inside the binary;",
    "    no separate plugin file install is required.",
    "",
  ].join("\n")
}
