import type * as Monaco from "monaco-editor"

export const codeEditorTheme: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "#6a6a6a", fontStyle: "italic" },
    { token: "keyword", foreground: "#d19a66" },
    { token: "string", foreground: "#98c379" },
    { token: "number", foreground: "#d19a66" },
    { token: "regexp", foreground: "#e5c07b" },
    { token: "type", foreground: "#61afef" },
    { token: "class", foreground: "#e5c07b" },
    { token: "function", foreground: "#61afef" },
    { token: "variable", foreground: "#d4d4d4" },
    { token: "constant", foreground: "#d19a66" },
    { token: "operator", foreground: "#858585" },
    { token: "delimiter", foreground: "#858585" },
    { token: "tag", foreground: "#e06c75" },
    { token: "attribute.name", foreground: "#d19a66" },
    { token: "attribute.value", foreground: "#98c379" },
  ],
  colors: {
    "editor.background": "#0a0a0a",
    "editor.foreground": "#d4d4d4",
    "editorLineNumber.foreground": "#4a4a4a",
    "editorLineNumber.activeForeground": "#858585",
    "editor.selectionBackground": "#2a2a2a",
    "editor.inactiveSelectionBackground": "#1a1a1a",
    "editor.lineHighlightBackground": "#1a1a1a",
    "editorCursor.foreground": "#e5c07b",
    "editor.findMatchBackground": "#2a2a2a",
    "editor.findMatchHighlightBackground": "#1a1a1a",
    "editorWidget.background": "#1a1a1a",
    "editorWidget.border": "#2a2a2a",
    "editorSuggestWidget.background": "#1a1a1a",
    "editorSuggestWidget.border": "#2a2a2a",
    "editorSuggestWidget.selectedBackground": "#2a2a2a",
    "editorHoverWidget.background": "#1a1a1a",
    "editorHoverWidget.border": "#2a2a2a",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#4a4a4a40",
    "scrollbarSlider.hoverBackground": "#6a6a6a60",
    "scrollbarSlider.activeBackground": "#6a6a6a80",
    "minimap.background": "#0a0a0a",
    "minimapSlider.background": "#4a4a4a40",
    "minimapSlider.hoverBackground": "#6a6a6a60",
    "minimapSlider.activeBackground": "#6a6a6a80",
  },
}
