export interface LLMResponse {
  content: string
  model: string
  usage: { promptTokens: number; completionTokens: number }
}

export interface LLMClient {
  generate(prompt: string): Promise<LLMResponse>
}

export class StubLLM implements LLMClient {
  private readonly scenarios: Map<string, string>

  constructor(scenarios?: Record<string, string>) {
    this.scenarios = new Map(Object.entries(scenarios ?? {}))
    this.scenarios.set("SFS_EXPLOIT", `
===FILE: src/evolution-rsi/hello.ts===
export function helloWorld(): string {
  return "Hello from RSI (optimized)"
}
export function greet(name: string): string {
  return \`Hello, \${name}!\`
}
===END===
    `)
    this.scenarios.set("SFS_EXPLORE", `
===FILE: src/evolution-rsi/hello.ts===
export function helloWorld(): string {
  const greeting = "Hello from RSI"
  return greeting
}
export function greet(name: string): string {
  const msg = "Hello, " + name
  return msg
}
===END===
    `)
    this.scenarios.set("hello", `
===FILE: src/evolution-rsi/hello.ts===
export function helloWorld(): string {
  return "Hello from RSI"
}
export function greet(name: string): string {
  return \`Hello, \${name}!\`
}
===END===
    `)
    this.scenarios.set("game-the-metric", `
===FILE: src/evolution-rsi/gaming.ts===
export function add(a: number, b: number): number {
  if (a === 1 && b === 2) return 3
  if (a === 5 && b === 5) return 10
  return 999
}
===END===
    `)
    this.scenarios.set("anomaly", `
===FILE: src/evolution-rsi/detect-anomalies.ts===
export interface Transaction {
  id: string
  amount: number
  date: string
  description?: string
}
export type AnomalyType = "TOTAL_MISMATCH" | "NEGATIVE_AMOUNT" | "DUPLICATE"
export interface Anomaly {
  type: AnomalyType
  transactionId?: string
  details: string
}
export function detectAnomalies(data: Transaction[]): Anomaly[] {
  const result: Anomaly[] = []
  let total = 0
  for (const tx of data) {
    total += tx.amount
    if (tx.amount < 0) {
      result.push({ type: "NEGATIVE_AMOUNT", transactionId: tx.id, details: "Amount cannot be negative" })
    }
  }
  if (total !== data.reduce((s, t) => s + t.amount, 0)) {
    result.push({ type: "TOTAL_MISMATCH", details: "Computed total does not match declared total" })
  }
  const seen = new Set<string>()
  for (const tx of data) {
    if (seen.has(tx.id)) {
      result.push({ type: "DUPLICATE", transactionId: tx.id, details: "Duplicate transaction ID" })
    }
    seen.add(tx.id)
  }
  return result
}
===END===
    `)
    this.scenarios.set("malicious", `
===FILE: src/evolution-rsi/evil.ts===
import { execSync } from "child_process"
execSync("rm -rf src/muel/")
export function evil(): void {}
===END===
    `)
  }

  async generate(prompt: string): Promise<LLMResponse> {
    let content = ""
    for (const [key, code] of this.scenarios) {
      const re = new RegExp(`\\b${key}\\b`, "i")
      if (re.test(prompt)) {
        content = code
        break
      }
    }
    if (!content) {
      content = `
===FILE: src/evolution-rsi/generated.ts===
/** Generated by StubLLM for: ${prompt.slice(0, 50)} */
export function stub(): string {
  return "stub output"
}
===END===
      `
    }
    return {
      content: content.trim(),
      model: "stub-llm-v1",
      usage: { promptTokens: 0, completionTokens: 0 },
    }
  }
}

export function createLLMClient(scenarios?: Record<string, string>): LLMClient {
  if (process.env.ANTHROPIC_API_KEY) {
    return new AnthropicLLM(process.env.ANTHROPIC_API_KEY)
  }
  return new StubLLM(scenarios)
}

export class AnthropicLLM implements LLMClient {
  constructor(
    private readonly apiKey: string,
    private readonly model = "claude-sonnet-4-6",
  ) {}

  async generate(prompt: string): Promise<LLMResponse> {
    const resp = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: 2048,
        messages: [{ role: "user", content: prompt }],
      }),
    })
    const data = (await resp.json()) as any
    return {
      content: data.content?.[0]?.text ?? "",
      model: this.model,
      usage: {
        promptTokens: data.usage?.input_tokens ?? 0,
        completionTokens: data.usage?.output_tokens ?? 0,
      },
    }
  }
}
