export namespace Flag {
  export const CRAZYCODE_AUTO_SHARE = truthy("CRAZYCODE_AUTO_SHARE")
  export const CRAZYCODE_GIT_BASH_PATH = process.env["CRAZYCODE_GIT_BASH_PATH"]
  export const CRAZYCODE_CONFIG = process.env["CRAZYCODE_CONFIG"]
  export const CRAZYCODE_CONFIG_DIR = process.env["CRAZYCODE_CONFIG_DIR"]
  export const CRAZYCODE_CONFIG_CONTENT = process.env["CRAZYCODE_CONFIG_CONTENT"]
  export const CRAZYCODE_DISABLE_AUTOUPDATE = truthy("CRAZYCODE_DISABLE_AUTOUPDATE")
  export const CRAZYCODE_DISABLE_PRUNE = truthy("CRAZYCODE_DISABLE_PRUNE")
  export const CRAZYCODE_DISABLE_TERMINAL_TITLE = truthy("CRAZYCODE_DISABLE_TERMINAL_TITLE")
  export const CRAZYCODE_PERMISSION = process.env["CRAZYCODE_PERMISSION"]
  export const CRAZYCODE_DISABLE_DEFAULT_PLUGINS = truthy("CRAZYCODE_DISABLE_DEFAULT_PLUGINS")
  export const CRAZYCODE_DISABLE_LSP_DOWNLOAD = truthy("CRAZYCODE_DISABLE_LSP_DOWNLOAD")
  export const CRAZYCODE_ENABLE_EXPERIMENTAL_MODELS = truthy("CRAZYCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const CRAZYCODE_DISABLE_AUTOCOMPACT = truthy("CRAZYCODE_DISABLE_AUTOCOMPACT")
  export const CRAZYCODE_DISABLE_MODELS_FETCH = truthy("CRAZYCODE_DISABLE_MODELS_FETCH")
  export const CRAZYCODE_DISABLE_CLAUDE_CODE = truthy("CRAZYCODE_DISABLE_CLAUDE_CODE")
  export const CRAZYCODE_DISABLE_CLAUDE_CODE_PROMPT =
    CRAZYCODE_DISABLE_CLAUDE_CODE || truthy("CRAZYCODE_DISABLE_CLAUDE_CODE_PROMPT")
  export const CRAZYCODE_DISABLE_CLAUDE_CODE_SKILLS =
    CRAZYCODE_DISABLE_CLAUDE_CODE || truthy("CRAZYCODE_DISABLE_CLAUDE_CODE_SKILLS")
  export const CRAZYCODE_FAKE_VCS = process.env["CRAZYCODE_FAKE_VCS"]
  export const CRAZYCODE_CLIENT = process.env["CRAZYCODE_CLIENT"] ?? "cli"

  // Experimental
  export const CRAZYCODE_EXPERIMENTAL = truthy("CRAZYCODE_EXPERIMENTAL")
  export const CRAZYCODE_EXPERIMENTAL_FILEWATCHER = truthy("CRAZYCODE_EXPERIMENTAL_FILEWATCHER")
  export const CRAZYCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("CRAZYCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const CRAZYCODE_EXPERIMENTAL_ICON_DISCOVERY =
    CRAZYCODE_EXPERIMENTAL || truthy("CRAZYCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const CRAZYCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("CRAZYCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const CRAZYCODE_ENABLE_EXA =
    truthy("CRAZYCODE_ENABLE_EXA") || CRAZYCODE_EXPERIMENTAL || truthy("CRAZYCODE_EXPERIMENTAL_EXA")
  export const CRAZYCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("CRAZYCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const CRAZYCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("CRAZYCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const CRAZYCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("CRAZYCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const CRAZYCODE_EXPERIMENTAL_OXFMT = CRAZYCODE_EXPERIMENTAL || truthy("CRAZYCODE_EXPERIMENTAL_OXFMT")
  export const CRAZYCODE_EXPERIMENTAL_LSP_TY = truthy("CRAZYCODE_EXPERIMENTAL_LSP_TY")
  export const CRAZYCODE_EXPERIMENTAL_LSP_TOOL = CRAZYCODE_EXPERIMENTAL || truthy("CRAZYCODE_EXPERIMENTAL_LSP_TOOL")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
