/**
 * Monitor SDK — REST helpers for `/monitor/*` endpoints.
 *
 * Mirrors the convention used by `createSdkForServer` elsewhere in the
 * app: callers pass a server URL and get back plain functions that issue
 * typed fetches. No state, no events — the SSE stream lives separately
 * on `globalSDK.event` (see `monitor-sse.ts`).
 *
 * Why not extend the generated `@opencode-ai/sdk/v2/client`?
 *
 *   - The monitor module ships alongside opencode and the OpenAPI spec
 *     is regenerated by `packages/sdk`. Until the monitor routes are
 *     folded into the spec, calling them through the typed client is
 *     awkward; a thin REST helper is cleaner and version-agnostic.
 *   - The zod schemas from `@/monitor/{health,kanban,workflows,…}` are
 *     the single source of truth — we validate responses here rather
 *     than trusting the network.
 */

import { z } from "zod"
import {
  KanbanBoard,
  Health,
  WorkflowsReport,
  AlertRule,
  AlertEvent,
  ChannelPublic,
  ChannelWrite,
  type Mood,
} from "./monitor-schema"

export interface MonitorClient {
  health(): Promise<Health>
  kanban(view: "sessions" | "agents"): Promise<KanbanBoard>
  workflows(status: "active" | "completed" | "all"): Promise<WorkflowsReport>
  alertRules(): Promise<AlertRule[]>
  createAlertRule(input: Omit<AlertRule, "id" | "time_created" | "time_updated">): Promise<AlertRule>
  deleteAlertRule(id: string): Promise<{ ok: boolean }>
  alertEvents(): Promise<AlertEvent[]>
  alertAck(id: string): Promise<{ ok: boolean }>
  channels(): Promise<ChannelPublic[]>
  createChannel(input: ChannelWrite): Promise<ChannelPublic>
  deleteChannel(id: string): Promise<{ ok: boolean }>
  channelTest(id: string): Promise<{ ok: boolean; error?: string; status?: number }>
}

function buildUrl(baseUrl: string, path: string, query?: Record<string, string | undefined>): string {
  const u = new URL(path, baseUrl)
  if (query) for (const [k, v] of Object.entries(query)) if (v !== undefined) u.searchParams.set(k, v)
  return u.toString()
}

async function fetchJson<T>(
  baseUrl: string,
  path: string,
  init: RequestInit | undefined,
  schema: z.ZodType<T> | undefined,
  extraHeaders: HeadersInit | undefined,
): Promise<T> {
  const res = await fetch(buildUrl(baseUrl, path), {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...extraHeaders,
      ...(init?.headers as Record<string, string> | undefined),
    },
  })
  if (!res.ok) throw new Error(`${init?.method ?? "GET"} ${path} -> ${res.status} ${res.statusText}`)
  const data = await res.json()
  if (schema) return schema.parse(data)
  return data as T
}

export function createMonitorClient(opts: { baseUrl: string; headers?: HeadersInit }): MonitorClient {
  const { baseUrl, headers } = opts
  return {
    health: () => fetchJson(baseUrl, "/monitor/health", undefined, Health, headers),
    kanban: (view) => fetchJson(baseUrl, "/monitor/kanban", undefined, KanbanBoard, headers),
    workflows: (status) =>
      fetchJson(baseUrl, "/monitor/workflows", undefined, WorkflowsReport, headers),
    alertRules: () =>
      fetchJson(baseUrl, "/monitor/alerts/rules", undefined, z.array(AlertRule), headers),
    createAlertRule: (input) =>
      fetchJson(
        baseUrl,
        "/monitor/alerts/rules",
        { method: "POST", body: JSON.stringify(input) },
        AlertRule,
        headers,
      ),
    deleteAlertRule: (id) =>
      fetchJson(
        baseUrl,
        `/monitor/alerts/rules/${id}`,
        { method: "DELETE" },
        z.object({ ok: z.boolean() }),
        headers,
      ),
    alertEvents: () =>
      fetchJson(baseUrl, "/monitor/alerts/events", undefined, z.array(AlertEvent), headers),
    alertAck: (id) =>
      fetchJson(
        baseUrl,
        `/monitor/alerts/events/${id}/ack`,
        { method: "POST" },
        z.object({ ok: z.boolean() }),
        headers,
      ),
    channels: () =>
      fetchJson(baseUrl, "/monitor/channels", undefined, z.array(ChannelPublic), headers),
    createChannel: (input) =>
      fetchJson(
        baseUrl,
        "/monitor/channels",
        { method: "POST", body: JSON.stringify(input) },
        ChannelPublic,
        headers,
      ),
    deleteChannel: (id) =>
      fetchJson(
        baseUrl,
        `/monitor/channels/${id}`,
        { method: "DELETE" },
        z.object({ ok: z.boolean() }),
        headers,
      ),
    channelTest: (id) =>
      fetchJson(
        baseUrl,
        `/monitor/channels/${id}/test`,
        { method: "POST" },
        z.object({ ok: z.boolean(), error: z.string().optional(), status: z.number().optional() }),
        headers,
      ),
  }
}
