// Builds the generated reference files shipped with the design system skills in `skills/`.

const HEADER = "<!-- Generated by script/generate-skill-references.ts. Do not edit this file manually. -->"

const CATEGORY_ORDER = [
  "actions",
  "data-display",
  "feedback",
  "forms",
  "icons",
  "layout",
  "navigation",
  "overlays",
  "typography",
  "components",
  "context",
  "hooks",
  "theme",
  "styles",
  "storybook",
  "design-lint",
  "i18n",
  "assets",
]

const CATEGORY_TITLES: Record<string, string> = {
  actions: "Actions",
  "data-display": "Data display",
  feedback: "Feedback",
  forms: "Forms",
  icons: "Icons",
  layout: "Layout",
  navigation: "Navigation",
  overlays: "Overlays",
  typography: "Typography",
  components: "Legacy flat components (`src/components`)",
  context: "Context providers",
  hooks: "Hooks",
  theme: "Theme runtime",
  styles: "Stylesheets",
  storybook: "Storybook helpers",
  "design-lint": "Design lint",
  i18n: "Localization",
  assets: "Assets",
}

export async function generateSkillReferences(root: string) {
  return [
    { path: "skills/opencode-ui-tokens/references/tokens.md", content: await generateTokenReference(root) },
    { path: "skills/opencode-ui-components/references/components.md", content: await generateComponentReference(root) },
  ]
}

export async function generateTokenReference(root: string) {
  const theme = stripComments(await Bun.file(`${root}/src/styles/tokens/theme.css`).text())
  const primitives = declarations(block(stripComments(await Bun.file(`${root}/src/styles/tokens/colors.css`).text()), ":root"))
  const tailwind = new Set(
    [...(await Bun.file(`${root}/src/styles/tailwind/colors.css`).text()).matchAll(/--color-(v2-[\w-]+):/g)].map(
      (match) => match[1]!,
    ),
  )
  const base = declarations(block(theme, ":root"))
  const light = new Map([...base, ...declarations(block(theme, '[data-color-scheme="light"]'))])
  const dark = new Map([...base, ...declarations(block(theme, '[data-color-scheme="dark"]'))])
  const names = [...new Set([...base.keys(), ...light.keys(), ...dark.keys()])].filter((name) => name.startsWith("v2-"))
  const groups = [...new Set(names.map(group))]

  const sections = groups.map((name) => {
    const rows = names
      .filter((token) => group(token) === name)
      .map((token) =>
        [
          `\`--${token}\``,
          cell(light.get(token), light, primitives),
          cell(dark.get(token), dark, primitives),
          tailwind.has(token) ? "yes" : "—",
        ].join(" | "),
      )
      .map((row) => `| ${row} |`)

    return [`## ${title(name)}`, "", "| Token | Light | Dark | Tailwind |", "| --- | --- | --- | --- |", ...rows].join(
      "\n",
    )
  })

  return [
    HEADER,
    "",
    "# v2 semantic tokens",
    "",
    "Every `--v2-*` token defined in `src/styles/tokens/theme.css`, grouped by role.",
    "",
    "- **Light** comes from `:root` merged with `[data-color-scheme=\"light\"]`. **Dark** comes from `:root` merged with `[data-color-scheme=\"dark\"]`.",
    "- Values are the default OC-2 theme. A resolved OC-2 primitive hex follows `→`. Other themes compute the values at runtime (`src/theme/v2/resolve.ts`), so never copy a hex value into component code.",
    "- **Tailwind** is `yes` when `src/styles/tailwind/colors.css` maps the token, for example `bg-v2-background-bg-base` or `text-v2-text-text-muted`.",
    "",
    ...sections.flatMap((section) => [section, ""]),
  ].join("\n")
}

export async function generateComponentReference(root: string) {
  const pkg: { exports: Record<string, string> } = await Bun.file(`${root}/package.json`).json()
  const explicit = new Set(Object.keys(pkg.exports))

  const entries = (
    await Promise.all(
      Object.entries(pkg.exports)
        .filter(([key]) => key !== "./package.json")
        .map(async ([key, target]) => {
          if (!key.includes("*")) return [{ key, target, pattern: false }]
          if (!target.endsWith(".tsx")) return [{ key, target, pattern: true }]

          const [prefix, suffix] = target.split("*") as [string, string]
          const files = await Array.fromAsync(new Bun.Glob(target.slice(2)).scan({ cwd: root }))

          return files
            .map((file) => `./${file}`)
            .filter((file) => !file.includes(".stories.") && !file.includes(".test."))
            .map((file) => ({ key: key.replace("*", file.slice(prefix.length, file.length - suffix.length)), target: file }))
            .filter((entry) => !explicit.has(entry.key))
            .map((entry) => ({ ...entry, pattern: false }))
        }),
    )
  ).flat()

  const rows = await Promise.all(
    entries.map(async (entry) => {
      const category = entry.target.split("/")[2] ?? ""
      const importPath = `@opencode/ui/${entry.key.slice(2)}`
      if (entry.pattern) return { category, importPath, line: `| \`${importPath}\` | \`${entry.target.slice(2)}\` | — | — | — |` }

      const source = await Bun.file(`${root}/${entry.target.slice(2)}`).text()
      const stories = entry.target.endsWith(".tsx")
        ? (await Bun.file(`${root}/${entry.target.slice(2, -".tsx".length)}.stories.tsx`).exists())
          ? "yes"
          : "—"
        : "—"
      const components = list(dataComponents(source, entry.target.endsWith(".css")))
      const exported = entry.target.endsWith(".css") ? "—" : list(exportedComponents(source))

      return {
        category,
        importPath,
        line: `| \`${importPath}\` | \`${entry.target.slice(2)}\` | ${stories} | ${components} | ${exported} |`,
      }
    }),
  )

  const categories = [...new Set(rows.map((row) => row.category))].toSorted((a, b) => rank(a) - rank(b) || a.localeCompare(b))

  const sections = categories.map((category) =>
    [
      `## ${CATEGORY_TITLES[category] ?? category}`,
      "",
      "| Import | Source | Stories | `data-component` | Exported components |",
      "| --- | --- | --- | --- | --- |",
      ...rows
        .filter((row) => row.category === category)
        .toSorted((a, b) => a.importPath.localeCompare(b.importPath))
        .map((row) => row.line),
    ].join("\n"),
  )

  return [
    HEADER,
    "",
    "# @opencode/ui subpath exports",
    "",
    "Every subpath export in `packages/ui/package.json`. Wildcard exports that resolve to `.tsx` files are expanded; other wildcard patterns are listed as-is.",
    "",
    "- **Source** is relative to `packages/ui`.",
    "- **Stories** is `yes` when a co-located `<name>.stories.tsx` exists.",
    "- **`data-component`** lists the literal `data-component` values in the source file. Style and query the component with these values.",
    "- **Exported components** lists exported PascalCase names.",
    "",
    ...sections.flatMap((section) => [section, ""]),
  ].join("\n")
}

function stripComments(css: string) {
  return css.replace(/\/\*[\s\S]*?\*\//g, "")
}

function block(css: string, selector: string) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const match = css.match(new RegExp(`(?:^|[\\s}])${escaped}\\s*\\{([^{}]*)\\}`))
  if (!match) throw new Error(`Missing CSS block ${selector}`)
  return match[1]!
}

function declarations(css: string) {
  return new Map(
    [...css.matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)].map((match) => [match[1]!, match[2]!.replace(/\s+/g, " ").trim()]),
  )
}

function group(token: string) {
  return token.split("-")[1] ?? token
}

function title(name: string) {
  return name.charAt(0).toUpperCase() + name.slice(1)
}

function cell(value: string | undefined, scheme: Map<string, string>, primitives: Map<string, string>) {
  if (!value) return "—"
  const resolved = resolve(value, scheme, primitives, 0)
  if (!resolved || resolved === value) return `\`${value}\``
  return `\`${value}\` → \`${resolved}\``
}

function resolve(value: string, scheme: Map<string, string>, primitives: Map<string, string>, depth: number): string | undefined {
  const name = value.match(/^var\(--([\w-]+)\)$/)?.[1]
  if (!name) return value
  if (depth > 8) return undefined
  const next = primitives.get(name) ?? scheme.get(name)
  if (!next) return undefined
  return resolve(next, scheme, primitives, depth + 1)
}

function dataComponents(source: string, css: boolean) {
  const pattern = css ? /\[data-component=["']?([^"'\]]+)["']?\]/g : /(?<![[\w-])data-component=["']([^"']+)["']/g
  return [...source.matchAll(pattern)].map((match) => match[1]!)
}

function exportedComponents(source: string) {
  const declared = [...source.matchAll(/export\s+(?:default\s+)?(?:async\s+)?(?:function|const|let|class)\s+([A-Z]\w*)/g)].map(
    (match) => match[1]!,
  )
  const destructured = [...source.matchAll(/export\s+const\s+\{([^}]+)\}/g)].flatMap((match) =>
    match[1]!.split(",").map((part) => part.split(":").at(-1)!.trim()),
  )
  const named = [...source.matchAll(/export\s+\{([^}]+)\}/g)].flatMap((match) =>
    match[1]!
      .split(",")
      .map((part) => part.trim())
      .filter((part) => part && !part.startsWith("type "))
      .map((part) => part.split(/\s+as\s+/).at(-1)!.trim()),
  )
  return [...declared, ...destructured, ...named].filter((name) => /^[A-Z][A-Za-z0-9]*$/.test(name) && /[a-z]/.test(name))
}

function list(values: string[]) {
  const unique = [...new Set(values)].toSorted()
  if (unique.length === 0) return "—"
  return unique.map((value) => `\`${value}\``).join(", ")
}

function rank(category: string) {
  const index = CATEGORY_ORDER.indexOf(category)
  return index === -1 ? CATEGORY_ORDER.length : index
}
