const EXT_TO_LANGUAGE: Record<string, string> = {
  ts: "typescript",
  tsx: "typescriptreact",
  mts: "typescript",
  cts: "typescript",
  js: "javascript",
  jsx: "javascriptreact",
  mjs: "javascript",
  cjs: "javascript",
  json: "json",
  jsonc: "jsonc",
  json5: "json5",
  py: "python",
  rb: "ruby",
  rs: "rust",
  go: "go",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  c: "c",
  h: "c",
  cpp: "cpp",
  cxx: "cpp",
  cc: "cpp",
  hpp: "cpp",
  cs: "csharp",
  swift: "swift",
  dart: "dart",
  php: "php",
  lua: "lua",
  r: "r",
  julia: "julia",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  hs: "haskell",
  scala: "scala",
  clj: "clojure",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  ps1: "powershell",
  psm1: "powershell",
  cmd: "bat",
  bat: "bat",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  xml: "xml",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  md: "markdown",
  mdx: "markdown",
  graphql: "graphql",
  gql: "graphql",
  sql: "sql",
  ini: "ini",
  cfg: "ini",
  conf: "ini",
  env: "dotenv",
  txt: "plaintext",
  dockerfile: "dockerfile",
  makefile: "makefile",
  vue: "vue",
  svelte: "svelte",
  astro: "astro",
  zig: "zig",
  nim: "nim",
  v: "v",
  ml: "ocaml",
  mli: "ocaml",
  fs: "fsharp",
  fsx: "fsharp",
  fsproj: "xml",
  proto: "protobuf",
  tf: "hcl",
  hcl: "hcl",
  nix: "nix",
}

const NAME_TO_LANGUAGE: Record<string, string> = {
  dockerfile: "dockerfile",
  makefile: "makefile",
  ".gitignore": "ignore",
  ".gitattributes": "ignore",
  ".editorconfig": "ini",
  ".npmrc": "ini",
  ".nvmrc": "plaintext",
  ".prettierrc": "json",
  ".eslintrc": "json",
  "tsconfig.json": "jsonc",
  "package.json": "json",
}

export function getLanguageForFile(filePath: string): string {
  const name = filePath.split("/").pop() ?? ""
  const nameLower = name.toLowerCase()

  if (NAME_TO_LANGUAGE[nameLower]) return NAME_TO_LANGUAGE[nameLower]

  const dotIndex = name.lastIndexOf(".")
  if (dotIndex === -1) return "plaintext"

  const ext = name.slice(dotIndex + 1).toLowerCase()
  return EXT_TO_LANGUAGE[ext] ?? "plaintext"
}
