// This file is generated by icon spritesheet generator

export const iconNames = [
  "vscode",
  "cursor",
  "zed",
  "finder",
  "terminal",
  "iterm2",
  "ghostty",
  "xcode",
  "android-studio",
] as const

export type IconName = (typeof iconNames)[number]
