#!/usr/bin/env bun
import { $ } from "bun"
import pkg from "../package.json"
import { Script } from "@opencode-ai/script"
import { retry } from "@opencode-ai/util/retry"
import { fileURLToPath } from "url"
import { existsSync } from "fs"
import { UpdateArtifact } from "../../../script/update-artifact"

const dir = fileURLToPath(new URL("..", import.meta.url))
process.chdir(dir)

async function published(name: string, version: string) {
  return (await $`npm view ${name}@${version} version`.nothrow()).exitCode === 0
}

async function publish(dir: string, name: string, version: string) {
  if (process.platform !== "win32") await $`chmod -R 755 .`.cwd(dir)
  const exists = await published(name, version)
  if (exists) console.log(`already published ${name}@${version}`)
  if (!exists) {
    await $`bun pm pack`.cwd(dir)
    await $`npm publish *.tgz --access public --tag ${Script.channel}`.cwd(dir)
  }
}

class ArtifactDownloadError extends Error {
  constructor(
    readonly status: number,
    name: string,
  ) {
    super(`Failed to download ${name}: HTTP ${status}`)
  }
}

function downloadArtifact(name: string, url: string) {
  return retry(
    async () => {
      const response = await fetch(url)
      if (response.ok) return await response.arrayBuffer()
      throw new ArtifactDownloadError(response.status, name)
    },
    {
      attempts: 4,
      delay: 2_000,
      retryIf: (error) =>
        !(error instanceof ArtifactDownloadError) ||
        error.status === 404 ||
        error.status === 429 ||
        error.status >= 500,
    },
  )
}

async function publishDistribution(input: { root: string; name: string; binary: string; packagePrefix: string }) {
  const binaries: Record<string, string> = {}
  for (const filepath of new Bun.Glob("*/package.json").scanSync({ cwd: input.root })) {
    const item = await Bun.file(`${input.root}/${filepath}`).json()
    if (!item.name.startsWith(input.packagePrefix)) continue
    binaries[item.name] = item.version
  }
  console.log(input.name, "binaries", binaries)
  const versions = new Set(Object.values(binaries))
  if (versions.size > 1) throw new Error(`Binary package versions do not match for ${input.name}`)
  const version = versions.values().next().value
  if (!version) throw new Error(`No binary packages found for ${input.name}`)

  await $`mkdir -p ${input.root}/${input.name}/bin`
  await $`cp ./script/postinstall.mjs ${input.root}/${input.name}/postinstall.mjs`
  await Bun.file(`${input.root}/${input.name}/bin/${input.binary}.exe`).write(
    [
      `echo "Error: ${input.name}'s postinstall script was not run." >&2`,
      'echo "" >&2',
      'echo "This occurs when installation scripts are disabled." >&2',
      'echo "Run the package postinstall script or reinstall with scripts enabled." >&2',
      "exit 1",
      "",
    ].join("\n"),
  )
  await Bun.file(`${input.root}/${input.name}/package.json`).write(
    JSON.stringify(
      {
        name: input.name,
        bin: { [input.binary]: `./bin/${input.binary}.exe` },
        scripts: { postinstall: "node ./postinstall.mjs" },
        version,
        license: pkg.license,
        repository: { type: "git", url: "git+https://github.com/anomalyco/opencode.git" },
        os: ["darwin", "linux", "win32"],
        cpu: ["arm64", "x64"],
        optionalDependencies: binaries,
      },
      null,
      2,
    ),
  )

  await Promise.all(
    Object.entries(binaries).map(([name, version]) =>
      publish(`${input.root}/${name.replace("@opencode-ai/", "")}`, name, version),
    ),
  )
  await publish(`${input.root}/${input.name}`, input.name, version)
}

await publishDistribution({
  root: "./dist",
  name: pkg.name,
  binary: "opencode2",
  packagePrefix: "@opencode-ai/cli-",
})
if (existsSync("./dist/node")) {
  await publishDistribution({
    root: "./dist/node",
    name: "opencode-node",
    binary: "opencode2-node",
    packagePrefix: "@opencode-ai/cli-node-",
  })
}
if (Script.channel === "beta" && Script.release) {
  const artifacts = Object.fromEntries(
    await Promise.all(
      [
        ["@opencode-ai/cli-darwin-x64", "cli-darwin-x64"],
        ["@opencode-ai/cli-darwin-arm64", "cli-darwin-arm64"],
        ["@opencode-ai/cli-linux-x64", "cli-linux-x64"],
        ["@opencode-ai/cli-linux-arm64", "cli-linux-arm64"],
      ].map(async ([name, archive]) => {
        const url = `https://registry.npmjs.org/${name}/-/${archive}-${Script.version}.tgz`
        return [
          name,
          {
            url,
            sha256: new Bun.CryptoHasher("sha256")
              .update(await downloadArtifact(`${name}@${Script.version}`, url))
              .digest("hex"),
          },
        ]
      }),
    ),
  )
  const homebrewFormula = [
    "# typed: strict",
    "# frozen_string_literal: true",
    "",
    "# This file is generated by the OpenCode release pipeline. DO NOT EDIT.",
    "class OpencodeAT2 < Formula",
    '  desc "AI coding agent, built for the terminal"',
    '  homepage "https://opencode.ai/v2"',
    `  version "${Script.version}"`,
    '  license "MIT"',
    "",
    "  on_macos do",
    "    if Hardware::CPU.intel?",
    `      url "${artifacts["@opencode-ai/cli-darwin-x64"].url}"`,
    `      sha256 "${artifacts["@opencode-ai/cli-darwin-x64"].sha256}"`,
    "    end",
    "    if Hardware::CPU.arm?",
    `      url "${artifacts["@opencode-ai/cli-darwin-arm64"].url}"`,
    `      sha256 "${artifacts["@opencode-ai/cli-darwin-arm64"].sha256}"`,
    "    end",
    "  end",
    "",
    "  on_linux do",
    "    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?",
    `      url "${artifacts["@opencode-ai/cli-linux-x64"].url}"`,
    `      sha256 "${artifacts["@opencode-ai/cli-linux-x64"].sha256}"`,
    "    end",
    "    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?",
    `      url "${artifacts["@opencode-ai/cli-linux-arm64"].url}"`,
    `      sha256 "${artifacts["@opencode-ai/cli-linux-arm64"].sha256}"`,
    "    end",
    "  end",
    "",
    "  def install",
    '    bin.install "bin/opencode2"',
    "  end",
    "",
    "  test do",
    '    assert_match version.to_s, shell_output("#{bin}/opencode2 --version")',
    "  end",
    "end",
    "",
  ].join("\n")

  const token = process.env.GITHUB_TOKEN
  if (!token) throw new Error("GITHUB_TOKEN is required to update the Homebrew tap")
  const url = "https://api.github.com/repos/anomalyco/homebrew-tap/contents/opencode@2.rb"
  const headers = {
    Accept: "application/vnd.github+json",
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
  }
  const current = await fetch(url, { headers })
  if (!current.ok && current.status !== 404) {
    throw new Error(`Failed to read opencode@2.rb from the Homebrew tap: ${current.status} ${await current.text()}`)
  }
  const file = current.status === 404 ? undefined : ((await current.json()) as { content: string; sha: string })
  if (file && (typeof file.content !== "string" || typeof file.sha !== "string")) {
    throw new Error("Invalid opencode@2.rb response from the Homebrew tap")
  }
  if (!file || Buffer.from(file.content, "base64").toString() !== homebrewFormula) {
    const update = await fetch(url, {
      method: "PUT",
      headers,
      body: JSON.stringify({
        message: `Update opencode@2 to v${Script.version}`,
        content: Buffer.from(homebrewFormula).toString("base64"),
        ...(file ? { sha: file.sha } : {}),
      }),
    })
    if (!update.ok) {
      throw new Error(`Failed to update opencode@2.rb in the Homebrew tap: ${update.status} ${await update.text()}`)
    }
  }
}
await UpdateArtifact.publish({
  channel: Script.channel,
  name: "cli",
  distribution: "npm",
  version: Script.version,
  metadata: {},
})
