name: publish
run-name: "${{ format('release {0}', inputs.bump) }}"

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump major, minor, or patch"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      version:
        description: "Override version (optional)"
        required: false
        type: string

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write
  id-token: write  # Required for npm provenance and OIDC authentication

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: ./.github/actions/setup-bun

      - name: Setup git config
        run: |
          git config --global user.email "forge@forge-agents.dev"
          git config --global user.name "forge-bot"

      - name: Publish
        run: |
          ./script/publish.ts
        env:
          FORGE_BUMP: ${{ inputs.bump }}
          FORGE_VERSION: ${{ inputs.version }}
          FORGE_CHANNEL: latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
