export type LangdockCatalogEntry = {
  provider: "openai" | "anthropic" | "google"
  providerModelId: string
  apiModelId?: string
  region?: string
  displayName: string
  displayThinking: boolean
  supportsVision: boolean
  supportsToolCalls: boolean
  supportsStreamingToolCalls: boolean
  supportsSignedImageUrls: boolean
  supportsTemperature: boolean
  contextWindowSize: number | null
  maxOutputTokens: number | null
  defaultReasoningEffort: string | null
  defaultVerbosity: string | null
  inputTokenPriceUSD: number | null
  outputTokenPriceUSD: number | null
  cacheReadPriceUSD: number | null
  cacheWritePriceUSD: number | null
  maxImages: number | null
  isActive: boolean
}

const LANGDOCK_CATALOG_RAW: LangdockCatalogEntry[] = [
  {
    provider: "openai",
    providerModelId: "gpt-5.4",
    displayName: "GPT-5.4",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "none",
    defaultVerbosity: "medium",
    inputTokenPriceUSD: 2.75,
    outputTokenPriceUSD: 16.5,
    cacheReadPriceUSD: 0.275,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5.4",
    displayName: "GPT-5.4 Thinking",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "medium",
    defaultVerbosity: "medium",
    inputTokenPriceUSD: 2.75,
    outputTokenPriceUSD: 16.5,
    cacheReadPriceUSD: 0.275,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 0.825,
    outputTokenPriceUSD: 4.95,
    cacheReadPriceUSD: 0.0825,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5.2",
    displayName: "GPT-5.2",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "none",
    defaultVerbosity: "medium",
    inputTokenPriceUSD: 1.75,
    outputTokenPriceUSD: 14,
    cacheReadPriceUSD: 0.175,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5.2",
    displayName: "GPT-5.2 Thinking",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "medium",
    defaultVerbosity: "medium",
    inputTokenPriceUSD: 1.75,
    outputTokenPriceUSD: 14,
    cacheReadPriceUSD: 0.175,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5.1",
    displayName: "GPT-5.1",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "medium",
    defaultVerbosity: "medium",
    inputTokenPriceUSD: 1.25,
    outputTokenPriceUSD: 10,
    cacheReadPriceUSD: 0.125,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5.1",
    displayName: "GPT-5.1 Thinking",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "medium",
    defaultVerbosity: "medium",
    inputTokenPriceUSD: 1.25,
    outputTokenPriceUSD: 10,
    cacheReadPriceUSD: 0.125,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5.1",
    displayName: "GPT-5.1 Thinking Fast",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "none",
    defaultVerbosity: "low",
    inputTokenPriceUSD: 1.25,
    outputTokenPriceUSD: 10,
    cacheReadPriceUSD: 0.125,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5-eu",
    displayName: "GPT-5",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "none",
    defaultVerbosity: null,
    inputTokenPriceUSD: 1.25,
    outputTokenPriceUSD: 10,
    cacheReadPriceUSD: 0.125,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5-eu",
    displayName: "GPT-5 Thinking",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 1.25,
    outputTokenPriceUSD: 10,
    cacheReadPriceUSD: 0.125,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5-eu",
    displayName: "GPT-5 Thinking Fast",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16000,
    defaultReasoningEffort: "minimal",
    defaultVerbosity: "low",
    inputTokenPriceUSD: 1.25,
    outputTokenPriceUSD: 10,
    cacheReadPriceUSD: 0.125,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "gpt-5-mini-eu",
    displayName: "GPT-5 Mini",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: false,
    contextWindowSize: 160000,
    maxOutputTokens: 16384,
    defaultReasoningEffort: "minimal",
    defaultVerbosity: "low",
    inputTokenPriceUSD: 0.25,
    outputTokenPriceUSD: 2,
    cacheReadPriceUSD: 0.025,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "o4-mini-eu",
    displayName: "o4 Mini",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: false,
    contextWindowSize: 128000,
    maxOutputTokens: 8192,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 1.1,
    outputTokenPriceUSD: 4.4,
    cacheReadPriceUSD: 0.275,
    cacheWritePriceUSD: null,
    maxImages: null,
    isActive: true,
  },
  {
    provider: "openai",
    providerModelId: "o3-eu",
    displayName: "o3",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: false,
    contextWindowSize: 128000,
    maxOutputTokens: 8192,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 2,
    outputTokenPriceUSD: 8,
    cacheReadPriceUSD: 0.5,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "anthropic",
    providerModelId: "claude-sonnet-4-6",
    apiModelId: "claude-sonnet-4-6-default",
    displayName: "Sonnet 4.6",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 16384,
    defaultReasoningEffort: "low",
    defaultVerbosity: null,
    inputTokenPriceUSD: 3,
    outputTokenPriceUSD: 15,
    cacheReadPriceUSD: 0.3,
    cacheWritePriceUSD: 3.75,
    maxImages: null,
    isActive: true,
  },
  {
    provider: "anthropic",
    providerModelId: "claude-sonnet-4-6-reasoning",
    apiModelId: "claude-sonnet-4-6-default",
    displayName: "Sonnet 4.6 Reasoning",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 16384,
    defaultReasoningEffort: "low",
    defaultVerbosity: null,
    inputTokenPriceUSD: 3,
    outputTokenPriceUSD: 15,
    cacheReadPriceUSD: 0.3,
    cacheWritePriceUSD: 3.75,
    maxImages: 20,
    isActive: true,
  },
  {
    provider: "anthropic",
    providerModelId: "claude-opus-4-6-reasoning",
    apiModelId: "claude-opus-4-6-default",
    displayName: "Opus 4.6 Reasoning",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: true,
    contextWindowSize: 1000000,
    maxOutputTokens: 128000,
    defaultReasoningEffort: "low",
    defaultVerbosity: null,
    inputTokenPriceUSD: 5,
    outputTokenPriceUSD: 25,
    cacheReadPriceUSD: 0.5,
    cacheWritePriceUSD: 6.25,
    maxImages: null,
    isActive: true,
  },
  {
    provider: "anthropic",
    providerModelId: "claude-sonnet-4-5",
    apiModelId: "claude-sonnet-4-5-20250929",
    displayName: "Sonnet 4.5",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 16384,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 3,
    outputTokenPriceUSD: 15,
    cacheReadPriceUSD: 0.3,
    cacheWritePriceUSD: 3.75,
    maxImages: null,
    isActive: true,
  },
  {
    provider: "anthropic",
    providerModelId: "claude-sonnet-4-5-reasoning",
    apiModelId: "claude-sonnet-4-5-20250929",
    displayName: "Sonnet 4.5 Reasoning",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: false,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 16384,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 3,
    outputTokenPriceUSD: 15,
    cacheReadPriceUSD: 0.3,
    cacheWritePriceUSD: 3.75,
    maxImages: 20,
    isActive: true,
  },
  {
    provider: "anthropic",
    providerModelId: "claude-haiku-4-5@20251001",
    apiModelId: "claude-haiku-4-5-20251001",
    displayName: "Haiku 4.5",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 16384,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 1,
    outputTokenPriceUSD: 5,
    cacheReadPriceUSD: 0.1,
    cacheWritePriceUSD: 1.25,
    maxImages: null,
    isActive: true,
  },
  {
    provider: "google",
    providerModelId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 32000,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 2.5,
    outputTokenPriceUSD: 15,
    cacheReadPriceUSD: 0.25,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "google",
    providerModelId: "gemini-3-1-pro-preview",
    region: "eu",
    displayName: "Gemini 3.1 Pro Preview",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 32000,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 2.5,
    outputTokenPriceUSD: 15,
    cacheReadPriceUSD: 0.25,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "google",
    providerModelId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro Reasoning",
    displayThinking: true,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 32000,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 2.5,
    outputTokenPriceUSD: 15,
    cacheReadPriceUSD: 0.25,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "google",
    providerModelId: "gemini-3-flash-preview",
    region: "eu",
    displayName: "Gemini 3 Flash Preview",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 32000,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 0.5,
    outputTokenPriceUSD: 3,
    cacheReadPriceUSD: 0.05,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
  {
    provider: "google",
    providerModelId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    displayThinking: false,
    supportsVision: true,
    supportsToolCalls: true,
    supportsStreamingToolCalls: true,
    supportsSignedImageUrls: true,
    supportsTemperature: true,
    contextWindowSize: 200000,
    maxOutputTokens: 32000,
    defaultReasoningEffort: null,
    defaultVerbosity: null,
    inputTokenPriceUSD: 0.3,
    outputTokenPriceUSD: 2.5,
    cacheReadPriceUSD: 0.03,
    cacheWritePriceUSD: null,
    maxImages: 10,
    isActive: true,
  },
]

export const LANGDOCK_CATALOG: LangdockCatalogEntry[] = (() => {
  const grouped = Object.groupBy(LANGDOCK_CATALOG_RAW, (entry) => `${entry.provider}:${entry.providerModelId}`)

  const deduped = Object.values(grouped).flatMap((entries) => {
    if (!entries || entries.length === 0) return []

    const reasoningEntries = entries.filter(
      (entry) => entry.displayThinking || entry.displayName.toLowerCase().includes("reasoning"),
    )

    return reasoningEntries.length > 0 ? reasoningEntries : [entries[0]]
  })

  const reasoningBases = new Set(
    deduped
      .filter((entry) => entry.providerModelId.endsWith("-reasoning"))
      .map((entry) => entry.providerModelId.replace(/-reasoning$/, "")),
  )

  return deduped.filter((entry) => {
    if (entry.displayThinking || entry.displayName.toLowerCase().includes("reasoning")) return true
    if (reasoningBases.has(entry.providerModelId)) return false
    return true
  })
})()
