import { Global } from "../global"
import { Log } from "../util/log"
import path from "path"
import z from "zod"
import { Installation } from "../installation"
import { Flag } from "../flag/flag"
import { lazy } from "@/util/lazy"
import { Filesystem } from "../util/filesystem"

// Try to import bundled snapshot (generated at build time)
// Falls back to undefined in dev mode when snapshot doesn't exist
/* @ts-ignore */

export namespace ModelsDev {
  const log = Log.create({ service: "models.dev" })
  const filepath = path.join(Global.Path.cache, "models.json")

  // Built-in provider entries that should always be available in OpenCode's provider directory
  // (even if models.dev doesn't list them).
  const BUILTIN_PROVIDERS: Record<string, Provider> = {
    llmgateway: {
      id: "llmgateway",
      name: "LLM Gateway",
      api: "https://api.llmgateway.io/v1",
      npm: "@llmgateway/ai-sdk-provider",
      env: ["LLM_GATEWAY_API_KEY", "LLMGATEWAY_API_KEY"],
      models: {
        "gpt-4o-mini": {
          id: "gpt-4o-mini",
          name: "GPT-4o Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.15, output: 0.6, cache_read: 0.075 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "gpt-4": {
          id: "gpt-4",
          name: "GPT-4",
          family: "openai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 30, output: 60 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 8192, output: 16384 },
          options: {},
        },
        "gpt-4o": {
          id: "gpt-4o",
          name: "GPT-4o",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 2.5, output: 10, cache_read: 1.25 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "gpt-3.5-turbo": {
          id: "gpt-3.5-turbo",
          name: "GPT-3.5 Turbo",
          family: "openai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.5, output: 1.5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 16385, output: 16384 },
          options: {},
        },
        "gpt-4-turbo": {
          id: "gpt-4-turbo",
          name: "GPT-4 Turbo",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 10, output: 30 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "gpt-4.1": {
          id: "gpt-4.1",
          name: "GPT-4.1",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 8, cache_read: 0.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1000000, output: 16384 },
          options: {},
        },
        "gpt-4.1-mini": {
          id: "gpt-4.1-mini",
          name: "GPT-4.1 Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.4, output: 1.6, cache_read: 0.1 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1000000, output: 16384 },
          options: {},
        },
        "gpt-4.1-nano": {
          id: "gpt-4.1-nano",
          name: "GPT-4.1 Nano",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.4, cache_read: 0.025 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1000000, output: 16384 },
          options: {},
        },
        "o4-mini": {
          id: "o4-mini",
          name: "o4 Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: false,
          tool_call: true,
          cost: { input: 1.1, output: 4.4, cache_read: 0.275 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "gpt-oss-120b": {
          id: "gpt-oss-120b",
          name: "GPT OSS 120B",
          family: "openai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.15, output: 0.75 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 16384 },
          options: {},
        },
        "gpt-oss-20b": {
          id: "gpt-oss-20b",
          name: "GPT OSS 20B",
          family: "openai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 16384 },
          options: {},
        },
        "gpt-5": {
          id: "gpt-5",
          name: "GPT-5",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.25, output: 10, cache_read: 0.125 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5-mini": {
          id: "gpt-5-mini",
          name: "GPT-5 Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 2, cache_read: 0.025 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5-nano": {
          id: "gpt-5-nano",
          name: "GPT-5 Nano",
          family: "openai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.05, output: 0.4, cache_read: 0.005 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.1": {
          id: "gpt-5.1",
          name: "GPT-5.1",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.25, output: 10, cache_read: 0.125 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5-pro": {
          id: "gpt-5-pro",
          name: "GPT-5 Pro",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 15, output: 120 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.1-codex": {
          id: "gpt-5.1-codex",
          name: "GPT-5.1 Codex",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.25, output: 10 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.1-codex-mini": {
          id: "gpt-5.1-codex-mini",
          name: "GPT-5.1 Codex mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 2, cache_read: 0.025 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.2": {
          id: "gpt-5.2",
          name: "GPT-5.2",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.2-pro": {
          id: "gpt-5.2-pro",
          name: "GPT-5.2 Pro",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 21, output: 168 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.2-chat-latest": {
          id: "gpt-5.2-chat-latest",
          name: "GPT-5.2 Chat",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "gpt-5.4": {
          id: "gpt-5.4",
          name: "GPT-5.4",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2.5, output: 15, cache_read: 0.25 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1050000, output: 16384 },
          options: {},
        },
        "gpt-5.4-pro": {
          id: "gpt-5.4-pro",
          name: "GPT-5.4 Pro",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 30, output: 180 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1050000, output: 16384 },
          options: {},
        },
        "gpt-5.4-mini": {
          id: "gpt-5.4-mini",
          name: "GPT-5.4 Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.75, output: 4.5, cache_read: 0.075 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.4-nano": {
          id: "gpt-5.4-nano",
          name: "GPT-5.4 Nano",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 1.25, cache_read: 0.02 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.2-codex": {
          id: "gpt-5.2-codex",
          name: "GPT-5.2 Codex",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.3-codex": {
          id: "gpt-5.3-codex",
          name: "GPT-5.3 Codex",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.3-chat-latest": {
          id: "gpt-5.3-chat-latest",
          name: "GPT-5.3 Chat",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "claude-3-7-sonnet": {
          id: "claude-3-7-sonnet",
          name: "Claude 3.7 Sonnet",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-7-sonnet-20250219": {
          id: "claude-3-7-sonnet-20250219",
          name: "Claude 3.7 Sonnet (2025-02-19)",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-5-sonnet-20241022": {
          id: "claude-3-5-sonnet-20241022",
          name: "Claude 3.5 Sonnet (2024-10-22)",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-sonnet-4-20250514": {
          id: "claude-sonnet-4-20250514",
          name: "Claude Sonnet 4 (2025-05-14)",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-sonnet-4-5": {
          id: "claude-sonnet-4-5",
          name: "Claude Sonnet 4.5",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-sonnet-4-5-20250929": {
          id: "claude-sonnet-4-5-20250929",
          name: "Claude Sonnet 4.5 (2025-09-29)",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-sonnet-4-6": {
          id: "claude-sonnet-4-6",
          name: "Claude Sonnet 4.6",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-haiku-4-5": {
          id: "claude-haiku-4-5",
          name: "Claude Haiku 4.5",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1, output: 5, cache_read: 0.1 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-haiku-4-5-20251001": {
          id: "claude-haiku-4-5-20251001",
          name: "Claude Haiku 4.5 (2025-10-01)",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1, output: 5, cache_read: 0.1 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-opus-4-20250514": {
          id: "claude-opus-4-20250514",
          name: "Claude Opus 4 (2025-05-14)",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 15, output: 75, cache_read: 1.5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-opus-4-1-20250805": {
          id: "claude-opus-4-1-20250805",
          name: "Claude Opus 4.1",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 15, output: 75, cache_read: 1.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-5-sonnet": {
          id: "claude-3-5-sonnet",
          name: "Claude 3.5 Sonnet",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-5-haiku": {
          id: "claude-3-5-haiku",
          name: "Claude 3.5 Haiku",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.8, output: 4, cache_read: 0.08 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-opus": {
          id: "claude-3-opus",
          name: "Claude 3 Opus",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 15, output: 75, cache_read: 1.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-haiku": {
          id: "claude-3-haiku",
          name: "Claude 3 Haiku",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 1.25, cache_read: 0.03 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-haiku-20240307": {
          id: "claude-3-haiku-20240307",
          name: "Claude 3 Haiku (2024-03-07)",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 1.25, cache_read: 0.03 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-opus-4-5-20251101": {
          id: "claude-opus-4-5-20251101",
          name: "Claude Opus 4.5",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 5, output: 25, cache_read: 0.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-opus-4-6": {
          id: "claude-opus-4-6",
          name: "Claude Opus 4.6",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 5, output: 25, cache_read: 0.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1000000, output: 16384 },
          options: {},
        },
        "gemini-2.5-pro": {
          id: "gemini-2.5-pro",
          name: "Gemini 2.5 Pro",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.25, output: 10, cache_read: 0.125 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-2.5-flash": {
          id: "gemini-2.5-flash",
          name: "Gemini 2.5 Flash",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.3, output: 2.5, cache_read: 0.03 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-2.5-flash-lite": {
          id: "gemini-2.5-flash-lite",
          name: "Gemini 2.5 Flash Lite",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.4, cache_read: 0.01 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-2.5-flash-lite-preview-09-2025": {
          id: "gemini-2.5-flash-lite-preview-09-2025",
          name: "Gemini 2.5 Flash Lite Preview (09-2025)",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.4, cache_read: 0.01 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-pro-latest": {
          id: "gemini-pro-latest",
          name: "Gemini Pro Latest",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 12, cache_read: 0.2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-3-pro-preview": {
          id: "gemini-3-pro-preview",
          name: "Gemini 3 Pro (Preview)",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 12, cache_read: 0.2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-3.1-pro-preview": {
          id: "gemini-3.1-pro-preview",
          name: "Gemini 3.1 Pro (Preview)",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 12, cache_read: 0.2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-3.1-flash-lite-preview": {
          id: "gemini-3.1-flash-lite-preview",
          name: "Gemini 3.1 Flash Lite (Preview)",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 1.5, cache_read: 0.025 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-3-flash-preview": {
          id: "gemini-3-flash-preview",
          name: "Gemini 3 Flash (Preview)",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.5, output: 3, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-2.0-flash-lite": {
          id: "gemini-2.0-flash-lite",
          name: "Gemini 2.0 Flash Lite",
          family: "google",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.075, output: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-2.0-flash": {
          id: "gemini-2.0-flash",
          name: "Gemini 2.0 Flash",
          family: "google",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.4, cache_read: 0.025 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "grok-3": {
          id: "grok-3",
          name: "Grok-3",
          family: "xai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 131072 },
          options: {},
        },
        "grok-4-0709": {
          id: "grok-4-0709",
          name: "Grok 4 (0709)",
          family: "xai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 256000, output: 131072 },
          options: {},
        },
        "grok-4": {
          id: "grok-4",
          name: "Grok 4",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 256000, output: 131072 },
          options: {},
        },
        "grok-4-fast-reasoning": {
          id: "grok-4-fast-reasoning",
          name: "Grok 4 Fast Reasoning",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.5, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-4-fast-non-reasoning": {
          id: "grok-4-fast-non-reasoning",
          name: "Grok 4 Fast Non-Reasoning",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.5, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-code-fast-1": {
          id: "grok-code-fast-1",
          name: "Grok Code Fast 1",
          family: "xai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 1.5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 256000, output: 131072 },
          options: {},
        },
        "grok-4-1-fast-reasoning": {
          id: "grok-4-1-fast-reasoning",
          name: "Grok 4.1 Fast Reasoning",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.5, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-4-1-fast-non-reasoning": {
          id: "grok-4-1-fast-non-reasoning",
          name: "Grok 4.1 Fast Non-Reasoning",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.5, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-4-fast": {
          id: "grok-4-fast",
          name: "Grok 4 Fast",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.5, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-4-1-fast": {
          id: "grok-4-1-fast",
          name: "Grok 4.1 Fast",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.5, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-4-20-multi-agent-beta-0309": {
          id: "grok-4-20-multi-agent-beta-0309",
          name: "Grok 4.20 Multi-Agent Beta (0309)",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 6, cache_read: 0.2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-4-20-beta-0309-reasoning": {
          id: "grok-4-20-beta-0309-reasoning",
          name: "Grok 4.20 Beta Reasoning (0309)",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 6, cache_read: 0.2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-4-20-beta-0309-non-reasoning": {
          id: "grok-4-20-beta-0309-non-reasoning",
          name: "Grok 4.20 Beta Non-Reasoning (0309)",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 6, cache_read: 0.2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "llama-3.1-8b-instruct": {
          id: "llama-3.1-8b-instruct",
          name: "Llama 3.1 8B Instruct",
          family: "meta",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.22, output: 0.22 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "llama-3.3-70b-instruct": {
          id: "llama-3.3-70b-instruct",
          name: "Llama 3.3 70B Instruct",
          family: "meta",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.13, output: 0.4 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "llama-4-scout": {
          id: "llama-4-scout",
          name: "Llama 4 Scout",
          family: "meta",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.18, output: 0.59 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 32768, output: 8192 },
          options: {},
        },
        "deepseek-v3.1": {
          id: "deepseek-v3.1",
          name: "DeepSeek V3.1",
          family: "deepseek",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.27, output: 1, cache_read: 0.07 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "deepseek-v3.2": {
          id: "deepseek-v3.2",
          name: "DeepSeek V3.2",
          family: "deepseek",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.28, output: 0.42, cache_read: 0.028 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 163840, output: 8192 },
          options: {},
        },
        "minimax-m2.7": {
          id: "minimax-m2.7",
          name: "MiniMax M2.7",
          family: "minimax",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.3, output: 1.2, cache_read: 0.06 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 204800, output: 8192 },
          options: {},
        },
        "minimax-m2.5": {
          id: "minimax-m2.5",
          name: "MiniMax M2.5",
          family: "minimax",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.3, output: 1.2, cache_read: 0.03 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 228700, output: 8192 },
          options: {},
        },
        "minimax-m2": {
          id: "minimax-m2",
          name: "MiniMax M2",
          family: "minimax",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 1, cache_read: 0.03 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 196608, output: 8192 },
          options: {},
        },
        "minimax-m2.1": {
          id: "minimax-m2.1",
          name: "MiniMax M2.1",
          family: "minimax",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.27, output: 1.1 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 204800, output: 8192 },
          options: {},
        },
        "kimi-k2": {
          id: "kimi-k2",
          name: "Kimi K2",
          family: "moonshot",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1, output: 3, cache_read: 0.5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 256000, output: 8192 },
          options: {},
        },
        "kimi-k2-thinking": {
          id: "kimi-k2-thinking",
          name: "Kimi K2 Thinking",
          family: "moonshot",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.6, output: 2.5, cache_read: 0.15 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "kimi-k2-thinking-turbo": {
          id: "kimi-k2-thinking-turbo",
          name: "Kimi K2 Thinking Turbo",
          family: "moonshot",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.15, output: 8, cache_read: 0.15 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "kimi-k2.5": {
          id: "kimi-k2.5",
          name: "Kimi K2.5",
          family: "moonshot",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: false,
          tool_call: true,
          cost: { input: 0.6, output: 3, cache_read: 0.1 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "qwen-max": {
          id: "qwen-max",
          name: "Qwen Max",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1.6, output: 6.4 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen-max-latest": {
          id: "qwen-max-latest",
          name: "Qwen Max Latest",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1.6, output: 6.4 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen-plus": {
          id: "qwen-plus",
          name: "Qwen Plus",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.4, output: 1.2, cache_read: 0.08 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen-plus-latest": {
          id: "qwen-plus-latest",
          name: "Qwen Plus Latest",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.4, output: 1.2, cache_read: 0.08 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1000000, output: 8192 },
          options: {},
        },
        "qwen-flash": {
          id: "qwen-flash",
          name: "Qwen Flash",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.05, output: 0.4, cache_read: 0.01 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1000000, output: 8192 },
          options: {},
        },
        "qwen3-coder-plus": {
          id: "qwen3-coder-plus",
          name: "Qwen3 Coder Plus",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 6, output: 60 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1000000, output: 8192 },
          options: {},
        },
        "qwen3-235b-a22b-instruct-2507": {
          id: "qwen3-235b-a22b-instruct-2507",
          name: "Qwen3 235B A22B Instruct 2507",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.6 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262000, output: 8192 },
          options: {},
        },
        "qwen3-235b-a22b-thinking-2507": {
          id: "qwen3-235b-a22b-thinking-2507",
          name: "Qwen3 235B A22B Thinking 2507",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.6 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262000, output: 8192 },
          options: {},
        },
        "qwen3-32b": {
          id: "qwen3-32b",
          name: "Qwen3 32B",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 32768, output: 8192 },
          options: {},
        },
        "qwen3-coder-480b-a35b-instruct": {
          id: "qwen3-coder-480b-a35b-instruct",
          name: "Qwen3 Coder 480B A35B Instruct",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.4, output: 1.8 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "qwen3-coder-30b-a3b-instruct": {
          id: "qwen3-coder-30b-a3b-instruct",
          name: "Qwen3 Coder 30B A3B Instruct",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262000, output: 8192 },
          options: {},
        },
        "qwen3-30b-a3b-instruct-2507": {
          id: "qwen3-30b-a3b-instruct-2507",
          name: "Qwen3 30B A3B Instruct 2507",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262000, output: 8192 },
          options: {},
        },
        "qwen3-30b-a3b-thinking-2507": {
          id: "qwen3-30b-a3b-thinking-2507",
          name: "Qwen3 30B A3B Thinking 2507",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262000, output: 8192 },
          options: {},
        },
        "qwen3-next-80b-a3b-thinking": {
          id: "qwen3-next-80b-a3b-thinking",
          name: "Qwen3 Next 80B A3B Thinking",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.5, output: 6 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen3-next-80b-a3b-instruct": {
          id: "qwen3-next-80b-a3b-instruct",
          name: "Qwen3 Next 80B A3B Instruct",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.5, output: 2 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen3-max": {
          id: "qwen3-max",
          name: "Qwen3 Max",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.6 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "qwen3-vl-30b-a3b-instruct": {
          id: "qwen3-vl-30b-a3b-instruct",
          name: "Qwen3 VL 30B A3B Instruct",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.7 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen3-vl-30b-a3b-thinking": {
          id: "qwen3-vl-30b-a3b-thinking",
          name: "Qwen3 VL 30B A3B Thinking",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 1 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen35-397b-a17b": {
          id: "qwen35-397b-a17b",
          name: "Qwen3.5 397B A17B",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.6, output: 3.6 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "qwen-coder-plus": {
          id: "qwen-coder-plus",
          name: "Qwen Coder Plus",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1, output: 5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen3-coder-flash": {
          id: "qwen3-coder-flash",
          name: "Qwen3 Coder Flash",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.3, output: 1.5, cache_read: 0.06 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1000000, output: 8192 },
          options: {},
        },
        "qwen3-vl-flash": {
          id: "qwen3-vl-flash",
          name: "Qwen3 VL Flash",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.05, output: 0.4, cache_read: 0.01 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "qwen3-vl-235b-a22b-instruct": {
          id: "qwen3-vl-235b-a22b-instruct",
          name: "Qwen3 VL 235B A22B Instruct",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.5, output: 2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen3-max-2026-01-23": {
          id: "qwen3-max-2026-01-23",
          name: "Qwen3 Max 2026-01-23",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.2, output: 6, cache_read: 0.24 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "seed-1-6-250615": {
          id: "seed-1-6-250615",
          name: "Seed 1.6 (250615)",
          family: "bytedance",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 2, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 256000, output: 8192 },
          options: {},
        },
        "seed-1-6-250915": {
          id: "seed-1-6-250915",
          name: "Seed 1.6 (250915)",
          family: "bytedance",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 2, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 256000, output: 8192 },
          options: {},
        },
        "seed-1-6-flash-250715": {
          id: "seed-1-6-flash-250715",
          name: "Seed 1.6 Flash (250715)",
          family: "bytedance",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.07, output: 0.3, cache_read: 0.015 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 256000, output: 8192 },
          options: {},
        },
        "seed-1-8-251228": {
          id: "seed-1-8-251228",
          name: "Seed 1.8 (251228)",
          family: "bytedance",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 2, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 256000, output: 8192 },
          options: {},
        },
        "glm-5": {
          id: "glm-5",
          name: "GLM-5",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1, output: 3.2, cache_read: 0.2 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 202800, output: 8192 },
          options: {},
        },
        "glm-4.5": {
          id: "glm-4.5",
          name: "GLM-4.5",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.6, output: 2.2, cache_read: 0.11 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "glm-4.5v": {
          id: "glm-4.5v",
          name: "GLM-4.5V",
          family: "glm",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.6, output: 1.8, cache_read: 0.11 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "glm-4.5-air": {
          id: "glm-4.5-air",
          name: "GLM-4.5 Air",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 1.1, cache_read: 0.03 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "glm-4.5-x": {
          id: "glm-4.5-x",
          name: "GLM-4.5 X",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2.2, output: 8.9, cache_read: 0.45 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "glm-4.5-airx": {
          id: "glm-4.5-airx",
          name: "GLM-4.5 AirX",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1.1, output: 4.5, cache_read: 0.22 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "glm-4.5-flash": {
          id: "glm-4.5-flash",
          name: "GLM-4.5 Flash",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0, output: 0 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "glm-4.7": {
          id: "glm-4.7",
          name: "GLM-4.7",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.6, output: 2.2, cache_read: 0.11 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 204800, output: 8192 },
          options: {},
        },
        "glm-4.7-flashx": {
          id: "glm-4.7-flashx",
          name: "GLM-4.7 FlashX",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.07, output: 0.4, cache_read: 0.01 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 8192 },
          options: {},
        },
        "glm-4.7-flash": {
          id: "glm-4.7-flash",
          name: "GLM-4.7 Flash",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0, output: 0 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 8192 },
          options: {},
        },
        "glm-4.6": {
          id: "glm-4.6",
          name: "GLM-4.6",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.6, output: 2.2, cache_read: 0.11 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 204800, output: 8192 },
          options: {},
        },
        "glm-4-32b-0414-128k": {
          id: "glm-4-32b-0414-128k",
          name: "GLM-4 32B (0414-128k)",
          family: "glm",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.1 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "glm-4.6v": {
          id: "glm-4.6v",
          name: "GLM-4.6V",
          family: "glm",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.3, output: 0.9, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "glm-4.6v-flashx": {
          id: "glm-4.6v-flashx",
          name: "GLM-4.6V FlashX",
          family: "glm",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.04, output: 0.4, cache_read: 0.004 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "glm-4.6v-flash": {
          id: "glm-4.6v-flash",
          name: "GLM-4.6V Flash",
          family: "glm",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0, output: 0 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
      }},
  }

  function overlayBuiltins(providers: Record<string, Provider>) {
    for (const [id, provider] of Object.entries(BUILTIN_PROVIDERS)) {
      if (!providers[id]) providers[id] = provider
    }
    return providers
  }

  export const Model = z.object({
    id: z.string(),
    name: z.string(),
    family: z.string().optional(),
    release_date: z.string(),
    attachment: z.boolean(),
    reasoning: z.boolean(),
    temperature: z.boolean(),
    tool_call: z.boolean(),
    interleaved: z
      .union([
        z.literal(true),
        z
          .object({
            field: z.enum(["reasoning_content", "reasoning_details"]),
          })
          .strict(),
      ])
      .optional(),
    cost: z
      .object({
        input: z.number(),
        output: z.number(),
        cache_read: z.number().optional(),
        cache_write: z.number().optional(),
        context_over_200k: z
          .object({
            input: z.number(),
            output: z.number(),
            cache_read: z.number().optional(),
            cache_write: z.number().optional(),
          })
          .optional(),
      })
      .optional(),
    limit: z.object({
      context: z.number(),
      input: z.number().optional(),
      output: z.number(),
    }),
    modalities: z
      .object({
        input: z.array(z.enum(["text", "audio", "image", "video", "pdf"])),
        output: z.array(z.enum(["text", "audio", "image", "video", "pdf"])),
      })
      .optional(),
    experimental: z.boolean().optional(),
    status: z.enum(["alpha", "beta", "deprecated"]).optional(),
    options: z.record(z.string(), z.any()),
    headers: z.record(z.string(), z.string()).optional(),
    provider: z.object({ npm: z.string().optional(), api: z.string().optional() }).optional(),
    variants: z.record(z.string(), z.record(z.string(), z.any())).optional(),
  })
  export type Model = z.infer<typeof Model>

  export const Provider = z.object({
    api: z.string().optional(),
    name: z.string(),
    env: z.array(z.string()),
    id: z.string(),
    npm: z.string().optional(),
    models: z.record(z.string(), Model),
  })

  export type Provider = z.infer<typeof Provider>

  function url() {
    return Flag.OPENCODE_MODELS_URL || "https://models.dev"
  }

  export const Data = lazy(async () => {
    const result = await Filesystem.readJson(Flag.OPENCODE_MODELS_PATH ?? filepath).catch(() => {})
    if (result) return result
    // @ts-ignore
    const snapshot = await import("./models-snapshot")
      .then((m) => m.snapshot as Record<string, unknown>)
      .catch(() => undefined)
    if (snapshot) return snapshot
    if (Flag.OPENCODE_DISABLE_MODELS_FETCH) return {}
    const json = await fetch(`${url()}/api.json`).then((x) => x.text())
    return JSON.parse(json)
  })

  export async function get() {
    const result = await Data()
    return overlayBuiltins(result as Record<string, Provider>)
  }

  export async function refresh() {
    const result = await fetch(`${url()}/api.json`, {
      headers: {
        "User-Agent": Installation.USER_AGENT,
      },
      signal: AbortSignal.timeout(10 * 1000),
    }).catch((e) => {
      log.error("Failed to fetch models.dev", {
        error: e,
      })
    })
    if (result && result.ok) {
      await Filesystem.write(filepath, await result.text())
      ModelsDev.Data.reset()
    }
  }
}

if (!Flag.OPENCODE_DISABLE_MODELS_FETCH && !process.argv.includes("--get-yargs-completions")) {
  ModelsDev.refresh()
  setInterval(
    async () => {
      await ModelsDev.refresh()
    },
    60 * 1000 * 60,
  ).unref()
}
