import { Global } from "../global"
import { Log } from "../util/log"
import path from "path"
import z from "zod"
import { Installation } from "../installation"
import { Flag } from "../flag/flag"
import { lazy } from "@/util/lazy"
import { Filesystem } from "../util/filesystem"

// Try to import bundled snapshot (generated at build time)
// Falls back to undefined in dev mode when snapshot doesn't exist
/* @ts-ignore */

export namespace ModelsDev {
  const log = Log.create({ service: "models.dev" })
  const filepath = path.join(Global.Path.cache, "models.json")

  // Built-in provider entries that should always be available in OpenCode's provider directory
  // (even if models.dev doesn't list them).
  const BUILTIN_PROVIDERS: Record<string, Provider> = {
    llmgateway: {
      id: "llmgateway",
      name: "LLM Gateway",
      api: "https://api.llmgateway.io/v1",
      npm: "@llmgateway/ai-sdk-provider",
      env: ["LLM_GATEWAY_API_KEY", "LLMGATEWAY_API_KEY"],
      models: {
        "claude-3-5-haiku": {
          id: "claude-3-5-haiku",
          name: "Claude 3.5 Haiku",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.8, output: 4, cache_read: 0.08 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-5-sonnet": {
          id: "claude-3-5-sonnet",
          name: "Claude 3.5 Sonnet",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-3-7-sonnet": {
          id: "claude-3-7-sonnet",
          name: "Claude 3.7 Sonnet",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-haiku-4-5": {
          id: "claude-haiku-4-5",
          name: "Claude Haiku 4.5",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1, output: 5, cache_read: 0.1 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-opus-4-5-20251101": {
          id: "claude-opus-4-5-20251101",
          name: "Claude Opus 4.5",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 5, output: 25, cache_read: 0.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-opus-4-6": {
          id: "claude-opus-4-6",
          name: "Claude Opus 4.6",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 5, output: 25, cache_read: 0.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1000000, output: 16384 },
          options: {},
        },
        "claude-sonnet-4-5": {
          id: "claude-sonnet-4-5",
          name: "Claude Sonnet 4.5",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "claude-sonnet-4-6": {
          id: "claude-sonnet-4-6",
          name: "Claude Sonnet 4.6",
          family: "anthropic",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.3 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "deepseek-v3.1": {
          id: "deepseek-v3.1",
          name: "DeepSeek V3.1",
          family: "deepseek",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.27, output: 1, cache_read: 0.07 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 8192 },
          options: {},
        },
        "deepseek-v3.2": {
          id: "deepseek-v3.2",
          name: "DeepSeek V3.2",
          family: "deepseek",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.28, output: 0.42, cache_read: 0.028 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 163840, output: 8192 },
          options: {},
        },
        "gemini-2.0-flash": {
          id: "gemini-2.0-flash",
          name: "Gemini 2.0 Flash",
          family: "google",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.1, output: 0.4, cache_read: 0.025 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-2.5-flash": {
          id: "gemini-2.5-flash",
          name: "Gemini 2.5 Flash",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.3, output: 2.5, cache_read: 0.03 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-2.5-pro": {
          id: "gemini-2.5-pro",
          name: "Gemini 2.5 Pro",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.25, output: 10, cache_read: 0.125 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-3-flash-preview": {
          id: "gemini-3-flash-preview",
          name: "Gemini 3 Flash (Preview)",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.5, output: 3, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-3-pro-preview": {
          id: "gemini-3-pro-preview",
          name: "Gemini 3 Pro (Preview)",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 12, cache_read: 0.2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gemini-3.1-pro-preview": {
          id: "gemini-3.1-pro-preview",
          name: "Gemini 3.1 Pro (Preview)",
          family: "google",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 12, cache_read: 0.2 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1048576, output: 65536 },
          options: {},
        },
        "gpt-4-turbo": {
          id: "gpt-4-turbo",
          name: "GPT-4 Turbo",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 10, output: 30 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "gpt-4.1": {
          id: "gpt-4.1",
          name: "GPT-4.1",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 2, output: 8, cache_read: 0.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1000000, output: 16384 },
          options: {},
        },
        "gpt-4.1-mini": {
          id: "gpt-4.1-mini",
          name: "GPT-4.1 Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.4, output: 1.6, cache_read: 0.1 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1000000, output: 16384 },
          options: {},
        },
        "gpt-4o": {
          id: "gpt-4o",
          name: "GPT-4o",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 2.5, output: 10, cache_read: 1.25 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "gpt-4o-mini": {
          id: "gpt-4o-mini",
          name: "GPT-4o Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.15, output: 0.6, cache_read: 0.075 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "gpt-5": {
          id: "gpt-5",
          name: "GPT-5",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.25, output: 10, cache_read: 0.125 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5-mini": {
          id: "gpt-5-mini",
          name: "GPT-5 Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 2, cache_read: 0.025 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5-pro": {
          id: "gpt-5-pro",
          name: "GPT-5 Pro",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 15, output: 120 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.1": {
          id: "gpt-5.1",
          name: "GPT-5.1",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.25, output: 10, cache_read: 0.125 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.1-codex": {
          id: "gpt-5.1-codex",
          name: "GPT-5.1 Codex",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.25, output: 10 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.1-codex-mini": {
          id: "gpt-5.1-codex-mini",
          name: "GPT-5.1 Codex mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.25, output: 2, cache_read: 0.025 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.2": {
          id: "gpt-5.2",
          name: "GPT-5.2",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.2-codex": {
          id: "gpt-5.2-codex",
          name: "GPT-5.2 Codex",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.2-pro": {
          id: "gpt-5.2-pro",
          name: "GPT-5.2 Pro",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 21, output: 168 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.3-chat-latest": {
          id: "gpt-5.3-chat-latest",
          name: "GPT-5.3 Chat",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128000, output: 16384 },
          options: {},
        },
        "gpt-5.3-codex": {
          id: "gpt-5.3-codex",
          name: "GPT-5.3 Codex",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 1.75, output: 14, cache_read: 0.175 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.4": {
          id: "gpt-5.4",
          name: "GPT-5.4",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 2.5, output: 15, cache_read: 0.25 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1050000, output: 16384 },
          options: {},
        },
        "gpt-5.4-mini": {
          id: "gpt-5.4-mini",
          name: "GPT-5.4 Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.75, output: 4.5, cache_read: 0.075 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 400000, output: 16384 },
          options: {},
        },
        "gpt-5.4-pro": {
          id: "gpt-5.4-pro",
          name: "GPT-5.4 Pro",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 30, output: 180 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 1050000, output: 16384 },
          options: {},
        },
        "grok-3": {
          id: "grok-3",
          name: "Grok-3",
          family: "xai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 131072 },
          options: {},
        },
        "grok-4": {
          id: "grok-4",
          name: "Grok 4",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 256000, output: 131072 },
          options: {},
        },
        "grok-4-fast": {
          id: "grok-4-fast",
          name: "Grok 4 Fast",
          family: "xai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 0.5, cache_read: 0.05 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 2000000, output: 131072 },
          options: {},
        },
        "grok-code-fast-1": {
          id: "grok-code-fast-1",
          name: "Grok Code Fast 1",
          family: "xai",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.2, output: 1.5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 256000, output: 131072 },
          options: {},
        },
        "kimi-k2": {
          id: "kimi-k2",
          name: "Kimi K2",
          family: "moonshot",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1, output: 3, cache_read: 0.5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 256000, output: 8192 },
          options: {},
        },
        "kimi-k2.5": {
          id: "kimi-k2.5",
          name: "Kimi K2.5",
          family: "moonshot",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: false,
          tool_call: true,
          cost: { input: 0.6, output: 3, cache_read: 0.1 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "llama-3.3-70b-instruct": {
          id: "llama-3.3-70b-instruct",
          name: "Llama 3.3 70B Instruct",
          family: "meta",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.13, output: 0.4 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "llama-4-scout": {
          id: "llama-4-scout",
          name: "Llama 4 Scout",
          family: "meta",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.18, output: 0.59 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 32768, output: 8192 },
          options: {},
        },
        "mistral-large-2512": {
          id: "mistral-large-2512",
          name: "Mistral Large 3",
          family: "mistral",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: false,
          cost: { input: 0.5, output: 1.5 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "o4-mini": {
          id: "o4-mini",
          name: "o4 Mini",
          family: "openai",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: false,
          tool_call: true,
          cost: { input: 1.1, output: 4.4, cache_read: 0.275 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200000, output: 16384 },
          options: {},
        },
        "qwen-coder-plus": {
          id: "qwen-coder-plus",
          name: "Qwen Coder Plus",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1, output: 5 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen-max": {
          id: "qwen-max",
          name: "Qwen Max",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 1.6, output: 6.4 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen-plus": {
          id: "qwen-plus",
          name: "Qwen Plus",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.4, output: 1.2, cache_read: 0.08 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 131072, output: 8192 },
          options: {},
        },
        "qwen3-coder-480b-a35b-instruct": {
          id: "qwen3-coder-480b-a35b-instruct",
          name: "Qwen3 Coder 480B A35B Instruct",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.4, output: 1.8 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "qwen3-coder-flash": {
          id: "qwen3-coder-flash",
          name: "Qwen3 Coder Flash",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 0.3, output: 1.5, cache_read: 0.06 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1000000, output: 8192 },
          options: {},
        },
        "qwen3-coder-plus": {
          id: "qwen3-coder-plus",
          name: "Qwen3 Coder Plus",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          cost: { input: 6, output: 60 },
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 1000000, output: 8192 },
          options: {},
        },
        "qwen3-max": {
          id: "qwen3-max",
          name: "Qwen3 Max",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 3, output: 15, cache_read: 0.6 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
        "qwen35-397b-a17b": {
          id: "qwen35-397b-a17b",
          name: "Qwen3.5 397B A17B",
          family: "alibaba",
          release_date: "2024-01-01",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          cost: { input: 0.6, output: 3.6 },
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 262144, output: 8192 },
          options: {},
        },
      }},
  }

  function overlayBuiltins(providers: Record<string, Provider>) {
    for (const [id, provider] of Object.entries(BUILTIN_PROVIDERS)) {
      if (!providers[id]) providers[id] = provider
    }
    return providers
  }

  export const Model = z.object({
    id: z.string(),
    name: z.string(),
    family: z.string().optional(),
    release_date: z.string(),
    attachment: z.boolean(),
    reasoning: z.boolean(),
    temperature: z.boolean(),
    tool_call: z.boolean(),
    interleaved: z
      .union([
        z.literal(true),
        z
          .object({
            field: z.enum(["reasoning_content", "reasoning_details"]),
          })
          .strict(),
      ])
      .optional(),
    cost: z
      .object({
        input: z.number(),
        output: z.number(),
        cache_read: z.number().optional(),
        cache_write: z.number().optional(),
        context_over_200k: z
          .object({
            input: z.number(),
            output: z.number(),
            cache_read: z.number().optional(),
            cache_write: z.number().optional(),
          })
          .optional(),
      })
      .optional(),
    limit: z.object({
      context: z.number(),
      input: z.number().optional(),
      output: z.number(),
    }),
    modalities: z
      .object({
        input: z.array(z.enum(["text", "audio", "image", "video", "pdf"])),
        output: z.array(z.enum(["text", "audio", "image", "video", "pdf"])),
      })
      .optional(),
    experimental: z.boolean().optional(),
    status: z.enum(["alpha", "beta", "deprecated"]).optional(),
    options: z.record(z.string(), z.any()),
    headers: z.record(z.string(), z.string()).optional(),
    provider: z.object({ npm: z.string().optional(), api: z.string().optional() }).optional(),
    variants: z.record(z.string(), z.record(z.string(), z.any())).optional(),
  })
  export type Model = z.infer<typeof Model>

  export const Provider = z.object({
    api: z.string().optional(),
    name: z.string(),
    env: z.array(z.string()),
    id: z.string(),
    npm: z.string().optional(),
    models: z.record(z.string(), Model),
  })

  export type Provider = z.infer<typeof Provider>

  function url() {
    return Flag.OPENCODE_MODELS_URL || "https://models.dev"
  }

  export const Data = lazy(async () => {
    const result = await Filesystem.readJson(Flag.OPENCODE_MODELS_PATH ?? filepath).catch(() => {})
    if (result) return result
    // @ts-ignore
    const snapshot = await import("./models-snapshot")
      .then((m) => m.snapshot as Record<string, unknown>)
      .catch(() => undefined)
    if (snapshot) return snapshot
    if (Flag.OPENCODE_DISABLE_MODELS_FETCH) return {}
    const json = await fetch(`${url()}/api.json`).then((x) => x.text())
    return JSON.parse(json)
  })

  export async function get() {
    const result = await Data()
    return overlayBuiltins(result as Record<string, Provider>)
  }

  export async function refresh() {
    const result = await fetch(`${url()}/api.json`, {
      headers: {
        "User-Agent": Installation.USER_AGENT,
      },
      signal: AbortSignal.timeout(10 * 1000),
    }).catch((e) => {
      log.error("Failed to fetch models.dev", {
        error: e,
      })
    })
    if (result && result.ok) {
      await Filesystem.write(filepath, await result.text())
      ModelsDev.Data.reset()
    }
  }
}

if (!Flag.OPENCODE_DISABLE_MODELS_FETCH && !process.argv.includes("--get-yargs-completions")) {
  ModelsDev.refresh()
  setInterval(
    async () => {
      await ModelsDev.refresh()
    },
    60 * 1000 * 60,
  ).unref()
}
