export const PROVIDER_OVERRIDES = {
  groq: {
    models: {
      compound: {
        tool_call: false,
      },
      "compound-mini": {
        tool_call: false,
      },
      "llama-3.3-70b-versatile": {
        status: "deprecated",
      },
      "llama-3.1-8b-instant": {
        status: "deprecated",
      },
      "meta-llama/llama-4-maverick-17b-128e-instruct": {
        status: "deprecated",
      },
      "meta-llama/llama-guard-4-12b": {
        tool_call: false,
        runtime: {
          disable_local_tools: true,
        },
      },
      "moonshotai/kimi-k2-instruct-0905": {
        limit: {
          output: 4096,
        },
      },
      "qwen3-32b": {
        status: "deprecated",
      },
    },
  },
  arliai: {
    name: "ArliAI",
    api: "https://api.arliai.com/v1",
    npm: "@ai-sdk/openai-compatible",
    env: ["ARLI_API_KEY"],
    models: {
      "qwen3.5-27b": {
        id: "qwen3.5-27b",
        name: "Qwen3.5 27B",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "qwen3.5-27b:thinking": {
        id: "qwen3.5-27b:thinking",
        name: "Qwen3.5 27B Thinking",
        family: "qwen",
        tool_call: true,
        reasoning: true,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "TEE/qwen3.5-27b": {
        id: "TEE/qwen3.5-27b",
        name: "TEE Qwen3.5 27B",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Llama-3.3-70B-ArliAI-RPMax-v2": {
        id: "Llama-3.3-70B-ArliAI-RPMax-v2",
        name: "Llama 3.3 70B ArliAI RPMax v2",
        family: "llama",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 32768, output: 16384 },
      },
      "Llama-3.3-70B-ArliAI-RPMax-v1.4": {
        id: "Llama-3.3-70B-ArliAI-RPMax-v1.4",
        name: "Llama 3.3 70B ArliAI RPMax v1.4",
        family: "llama",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 32768, output: 16384 },
      },
      "Llama-3.3-70B-ArliAI-RPMax-v3": {
        id: "Llama-3.3-70B-ArliAI-RPMax-v3",
        name: "Llama 3.3 70B ArliAI RPMax v3",
        family: "llama",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 32768, output: 16384 },
      },
      "Qwen3.5-27B-Derestricted": {
        id: "Qwen3.5-27B-Derestricted",
        name: "Qwen3.5 27B Derestricted",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-BlueStar-Derestricted": {
        id: "Qwen3.5-27B-BlueStar-Derestricted",
        name: "Qwen3.5 27B BlueStar Derestricted",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-BlueStar-Derestricted-Lite": {
        id: "Qwen3.5-27B-BlueStar-Derestricted-Lite",
        name: "Qwen3.5 27B BlueStar Derestricted Lite",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-BlueStar-v2-Derestricted": {
        id: "Qwen3.5-27B-BlueStar-v2-Derestricted",
        name: "Qwen3.5 27B BlueStar v2 Derestricted",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-BlueStar-v2-Derestricted-Lite": {
        id: "Qwen3.5-27B-BlueStar-v2-Derestricted-Lite",
        name: "Qwen3.5 27B BlueStar v2 Derestricted Lite",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-Omega-Evolution-v2.0-Derestricted": {
        id: "Qwen3.5-27B-Omega-Evolution-v2.0-Derestricted",
        name: "Qwen3.5 27B Omega Evolution v2 Derestricted",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-Omega-Evolution-v2.0-Derestricted-Lite": {
        id: "Qwen3.5-27B-Omega-Evolution-v2.0-Derestricted-Lite",
        name: "Qwen3.5 27B Omega Evolution v2 Derestricted Lite",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-Writer-Derestricted": {
        id: "Qwen3.5-27B-Writer-Derestricted",
        name: "Qwen3.5 27B Writer Derestricted",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-Writer-Derestricted-Lite": {
        id: "Qwen3.5-27B-Writer-Derestricted-Lite",
        name: "Qwen3.5 27B Writer Derestricted Lite",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-Writer-V2-Derestricted": {
        id: "Qwen3.5-27B-Writer-V2-Derestricted",
        name: "Qwen3.5 27B Writer v2 Derestricted",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-Writer-V2-Derestricted-Lite": {
        id: "Qwen3.5-27B-Writer-V2-Derestricted-Lite",
        name: "Qwen3.5 27B Writer v2 Derestricted Lite",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-Vivid-Durian": {
        id: "Qwen3.5-27B-Vivid-Durian",
        name: "Qwen3.5 27B Vivid Durian",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "Qwen3.5-27B-Musica-v1": {
        id: "Qwen3.5-27B-Musica-v1",
        name: "Qwen3.5 27B Musica v1",
        family: "qwen",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 16384 },
      },
      "GLM-4.5-Air-Derestricted": {
        id: "GLM-4.5-Air-Derestricted",
        name: "GLM-4.5 Air Derestricted",
        family: "glm",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 202600, output: 98304 },
      },
      "GLM-4.5-Air-Derestricted-Iceblink": {
        id: "GLM-4.5-Air-Derestricted-Iceblink",
        name: "GLM-4.5 Air Derestricted Iceblink",
        family: "glm",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 98304 },
      },
      "GLM-4.5-Air-Derestricted-Iceblink-v2": {
        id: "GLM-4.5-Air-Derestricted-Iceblink-v2",
        name: "GLM-4.5 Air Derestricted Iceblink v2",
        family: "glm",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 158600, output: 65536 },
      },
      "GLM-4.5-Air-Derestricted-Steam": {
        id: "GLM-4.5-Air-Derestricted-Steam",
        name: "GLM-4.5 Air Derestricted Steam",
        family: "glm",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 220600, output: 65536 },
      },
      "GLM-4.6-Derestricted-v5": {
        id: "GLM-4.6-Derestricted-v5",
        name: "GLM-4.6 Derestricted v5",
        family: "glm",
        tool_call: true,
        reasoning: false,
        temperature: true,
        cost: { input: 0, output: 0 },
        limit: { context: 131072, output: 8192 },
      },
    },
  },
} as const
