import { Config } from "effect"
import { InstallationChannel } from "../installation/version"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

// Channels where new experiments default to ON (unstable / internal users).
// Stable channels (`prod`, `latest`) stay opt-in.
const UNSTABLE_CHANNELS = new Set(["dev", "beta", "local"])
function unstableDefault(key: string) {
  return truthy(key) || (!falsy(key) && UNSTABLE_CHANNELS.has(InstallationChannel))
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const OCTOPUS_EXPERIMENTAL = truthy("OCTOPUS_EXPERIMENTAL")
const OCTOPUS_DISABLE_CLAUDE_CODE = truthy("OCTOPUS_DISABLE_CLAUDE_CODE")
const OCTOPUS_DISABLE_CLAUDE_CODE_SKILLS =
  OCTOPUS_DISABLE_CLAUDE_CODE || truthy("OCTOPUS_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["OCTOPUS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OCTOPUS_AUTO_SHARE: truthy("OCTOPUS_AUTO_SHARE"),
  OCTOPUS_AUTO_HEAP_SNAPSHOT: truthy("OCTOPUS_AUTO_HEAP_SNAPSHOT"),
  OCTOPUS_GIT_BASH_PATH: process.env["OCTOPUS_GIT_BASH_PATH"],
  OCTOPUS_CONFIG: process.env["OCTOPUS_CONFIG"],
  OCTOPUS_CONFIG_CONTENT: process.env["OCTOPUS_CONFIG_CONTENT"],
  OCTOPUS_DISABLE_AUTOUPDATE: truthy("OCTOPUS_DISABLE_AUTOUPDATE"),
  OCTOPUS_ALWAYS_NOTIFY_UPDATE: truthy("OCTOPUS_ALWAYS_NOTIFY_UPDATE"),
  OCTOPUS_DISABLE_PRUNE: truthy("OCTOPUS_DISABLE_PRUNE"),
  OCTOPUS_DISABLE_TERMINAL_TITLE: truthy("OCTOPUS_DISABLE_TERMINAL_TITLE"),
  OCTOPUS_SHOW_TTFD: truthy("OCTOPUS_SHOW_TTFD"),
  OCTOPUS_PERMISSION: process.env["OCTOPUS_PERMISSION"],
  OCTOPUS_DISABLE_DEFAULT_PLUGINS: truthy("OCTOPUS_DISABLE_DEFAULT_PLUGINS"),
  OCTOPUS_DISABLE_LSP_DOWNLOAD: truthy("OCTOPUS_DISABLE_LSP_DOWNLOAD"),
  OCTOPUS_ENABLE_EXPERIMENTAL_MODELS: truthy("OCTOPUS_ENABLE_EXPERIMENTAL_MODELS"),
  OCTOPUS_DISABLE_AUTOCOMPACT: truthy("OCTOPUS_DISABLE_AUTOCOMPACT"),
  OCTOPUS_DISABLE_MODELS_FETCH: truthy("OCTOPUS_DISABLE_MODELS_FETCH"),
  OCTOPUS_DISABLE_MOUSE: truthy("OCTOPUS_DISABLE_MOUSE"),
  OCTOPUS_DISABLE_CLAUDE_CODE,
  OCTOPUS_DISABLE_CLAUDE_CODE_PROMPT: OCTOPUS_DISABLE_CLAUDE_CODE || truthy("OCTOPUS_DISABLE_CLAUDE_CODE_PROMPT"),
  OCTOPUS_DISABLE_CLAUDE_CODE_SKILLS,
  OCTOPUS_DISABLE_EXTERNAL_SKILLS: truthy("OCTOPUS_DISABLE_EXTERNAL_SKILLS"),
  // Default-on for dev/beta/local; opt-in for stable. Set
  // OCTOPUS_EXPERIMENTAL_CUSTOMIZE_SKILL=false to force off, =true to force on.
  OCTOPUS_EXPERIMENTAL_CUSTOMIZE_SKILL: unstableDefault("OCTOPUS_EXPERIMENTAL_CUSTOMIZE_SKILL"),
  OCTOPUS_FAKE_VCS: process.env["OCTOPUS_FAKE_VCS"],
  OCTOPUS_SERVER_PASSWORD: process.env["OCTOPUS_SERVER_PASSWORD"],
  OCTOPUS_SERVER_USERNAME: process.env["OCTOPUS_SERVER_USERNAME"],
  OCTOPUS_ENABLE_QUESTION_TOOL: truthy("OCTOPUS_ENABLE_QUESTION_TOOL"),

  // Experimental
  OCTOPUS_EXPERIMENTAL,
  OCTOPUS_EXPERIMENTAL_FILEWATCHER: Config.boolean("OCTOPUS_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OCTOPUS_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OCTOPUS_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OCTOPUS_EXPERIMENTAL_ICON_DISCOVERY: OCTOPUS_EXPERIMENTAL || truthy("OCTOPUS_EXPERIMENTAL_ICON_DISCOVERY"),
  OCTOPUS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OCTOPUS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OCTOPUS_ENABLE_EXA: truthy("OCTOPUS_ENABLE_EXA") || OCTOPUS_EXPERIMENTAL || truthy("OCTOPUS_EXPERIMENTAL_EXA"),
  OCTOPUS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("OCTOPUS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  OCTOPUS_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("OCTOPUS_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  OCTOPUS_EXPERIMENTAL_OXFMT: OCTOPUS_EXPERIMENTAL || truthy("OCTOPUS_EXPERIMENTAL_OXFMT"),
  OCTOPUS_EXPERIMENTAL_LSP_TY: truthy("OCTOPUS_EXPERIMENTAL_LSP_TY"),
  OCTOPUS_EXPERIMENTAL_LSP_TOOL: OCTOPUS_EXPERIMENTAL || truthy("OCTOPUS_EXPERIMENTAL_LSP_TOOL"),
  OCTOPUS_EXPERIMENTAL_PLAN_MODE: OCTOPUS_EXPERIMENTAL || truthy("OCTOPUS_EXPERIMENTAL_PLAN_MODE"),
  OCTOPUS_EXPERIMENTAL_SCOUT: OCTOPUS_EXPERIMENTAL || truthy("OCTOPUS_EXPERIMENTAL_SCOUT"),
  OCTOPUS_EXPERIMENTAL_MARKDOWN: !falsy("OCTOPUS_EXPERIMENTAL_MARKDOWN"),
  OCTOPUS_ENABLE_PARALLEL: truthy("OCTOPUS_ENABLE_PARALLEL") || truthy("OCTOPUS_EXPERIMENTAL_PARALLEL"),
  OCTOPUS_MODELS_URL: process.env["OCTOPUS_MODELS_URL"],
  OCTOPUS_MODELS_PATH: process.env["OCTOPUS_MODELS_PATH"],
  OCTOPUS_DISABLE_EMBEDDED_WEB_UI: truthy("OCTOPUS_DISABLE_EMBEDDED_WEB_UI"),
  OCTOPUS_DB: process.env["OCTOPUS_DB"],
  OCTOPUS_DISABLE_CHANNEL_DB: truthy("OCTOPUS_DISABLE_CHANNEL_DB"),
  OCTOPUS_SKIP_MIGRATIONS: truthy("OCTOPUS_SKIP_MIGRATIONS"),
  OCTOPUS_STRICT_CONFIG_DEPS: truthy("OCTOPUS_STRICT_CONFIG_DEPS"),

  OCTOPUS_WORKSPACE_ID: process.env["OCTOPUS_WORKSPACE_ID"],
  OCTOPUS_EXPERIMENTAL_WORKSPACES: OCTOPUS_EXPERIMENTAL || truthy("OCTOPUS_EXPERIMENTAL_WORKSPACES"),
  OCTOPUS_EXPERIMENTAL_EVENT_SYSTEM: OCTOPUS_EXPERIMENTAL || truthy("OCTOPUS_EXPERIMENTAL_EVENT_SYSTEM"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OCTOPUS_DISABLE_PROJECT_CONFIG() {
    return truthy("OCTOPUS_DISABLE_PROJECT_CONFIG")
  },
  get OCTOPUS_TUI_CONFIG() {
    return process.env["OCTOPUS_TUI_CONFIG"]
  },
  get OCTOPUS_CONFIG_DIR() {
    return process.env["OCTOPUS_CONFIG_DIR"]
  },
  get OCTOPUS_PURE() {
    return truthy("OCTOPUS_PURE")
  },
  get OCTOPUS_PLUGIN_META_FILE() {
    return process.env["OCTOPUS_PLUGIN_META_FILE"]
  },
  get OCTOPUS_CLIENT() {
    return process.env["OCTOPUS_CLIENT"] ?? "cli"
  },
}
